import {
  chmodSync,
  mkdirSync,
  mkdtempSync,
  rmSync,
  writeFileSync
} from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const originalEnv = { ...process.env };
delete originalEnv.CHATKJB_SKIP_PROJECT_DIRECTORY_VALIDATION;
const directories: string[] = [];

beforeEach(() => {
  process.env = { ...originalEnv };
});

afterEach(() => {
  process.env = { ...originalEnv };
  vi.resetModules();
  for (const directory of directories.splice(0)) {
    rmSync(directory, { recursive: true, force: true });
  }
});

async function setup(token?: string, extra?: {
  token2?: string;
  token3?: string;
  telegramAllowedUserId?: string | undefined;
  telegramAllowedUserIds?: string;
  env?: Record<string, string>;
}) {
  const directory = mkdtempSync(join(tmpdir(), "telegram-claude-config-"));
  directories.push(directory);
  const project = join(directory, "project");
  mkdirSync(project);
  const projectsPath = join(directory, "projects.json");
  writeFileSync(projectsPath, JSON.stringify([
    { name: "test", cwd: project, defaultMode: "default" }
  ]));
  process.env = {
    HOME: directory,
    TELEGRAM_BOT_TOKEN: "1234567890:test-token",
    ...(extra && Object.hasOwn(extra, "telegramAllowedUserId")
      ? { TELEGRAM_ALLOWED_USER_ID: extra.telegramAllowedUserId }
      : { TELEGRAM_ALLOWED_USER_ID: "1" }),
    ...(extra?.telegramAllowedUserIds !== undefined
      ? { TELEGRAM_ALLOWED_USER_IDS: extra.telegramAllowedUserIds }
      : {}),
    TELEGRAM_CHAT_ID: "-1001",
    CHATKJB_ENV_PATH: join(directory, "missing.env"),
    PROJECTS_PATH: projectsPath,
    CODEX_HOME: join(directory, "codex-home"),
    CLAUDE_CODE_OAUTH_TOKEN: token ?? "",
    ...(extra?.token2 !== undefined ? { CLAUDE_CODE_OAUTH_TOKEN_2: extra.token2 } : {}),
    ...(extra?.token3 !== undefined ? { CLAUDE_CODE_OAUTH_TOKEN_3: extra.token3 } : {}),
    ...(extra?.env ?? {})
  };
  const { loadConfig } = await import("../src/config.js");
  return loadConfig();
}

describe("OAuth configuration", () => {
  it("disables the provider turn limit by default and supports an explicit limit", async () => {
    const unlimited = await setup("sk-ant-oat01-test_token-123");
    expect(unlimited.providerTurnTimeoutMs).toBeUndefined();

    const limited = await setup("sk-ant-oat01-test_token-123", {
      env: { PROVIDER_TURN_TIMEOUT_MINUTES: "45" }
    });
    expect(limited.providerTurnTimeoutMs).toBe(45 * 60_000);
  });

  it("requires at least one authenticated provider and still validates configured Claude tokens", async () => {
    await expect(setup()).rejects.toThrow("사용 가능한 AI 제공자 인증이 없습니다");
    await expect(setup("not-an-oauth-token")).rejects.toThrow(
      "CLAUDE_CODE_OAUTH_TOKEN must be generated by `claude setup-token`"
    );
  });

  it("loads a valid setup-token credential", async () => {
    const config = await setup("sk-ant-oat01-test_token-123");
    expect(config.claudeCodeOauthToken).toBe("sk-ant-oat01-test_token-123");
    expect(config.claudeCodeOauthTokens).toEqual(["sk-ant-oat01-test_token-123"]);
    expect(config.availableProviders).toEqual(["claude"]);
    expect(config.defaultProvider).toBe("claude");
    expect(config.claudeMemoryDir).toMatch(/\.claude\/memory$/);
    expect(config.agyMcpServers).toEqual([
      "llm-wiki",
      "obsidian",
      "outlook",
      "peekaboo",
      "playwright",
      "price-feed",
      "literature-evidence",
      "scihub"
    ]);
  });

  it("boots without Claude when a Codex ChatGPT account is authenticated", async () => {
    const codexHome = mkdtempSync(join(tmpdir(), "chatkjb-codex-only-"));
    directories.push(codexHome);
    writeFileSync(join(codexHome, "auth.json"), JSON.stringify({ auth_mode: "chatgpt" }));
    const config = await setup(undefined, { env: { CODEX_ACCOUNT_HOMES: codexHome } });
    expect(config.claudeCodeOauthToken).toBeUndefined();
    expect(config.claudeCodeOauthTokens).toEqual([]);
    expect(config.availableProviders).toEqual(["codex"]);
    expect(config.defaultProvider).toBe("codex");
  });

  it("detects Antigravity and Grok subscription logins independently", async () => {
    const home = mkdtempSync(join(tmpdir(), "chatkjb-provider-auth-"));
    directories.push(home);
    const agyCache = join(home, ".gemini", "antigravity-cli", "cache");
    const grokHome = join(home, ".grok");
    mkdirSync(agyCache, { recursive: true });
    mkdirSync(grokHome, { recursive: true });
    writeFileSync(join(agyCache, "onboarding.json"), JSON.stringify({ onboardingComplete: true }));
    writeFileSync(join(grokHome, "auth.json"), JSON.stringify({ issuer: { key: "token" } }));
    const { detectAuthenticatedProviders } = await import("../src/config.js");
    expect(detectAuthenticatedProviders({
      claudeOauthTokens: [],
      codexAccountHomes: [],
      home
    })).toEqual(["agy", "grok"]);
  });

  it("boots with an Antigravity-only OAuth installation", async () => {
    const home = mkdtempSync(join(tmpdir(), "chatkjb-agy-only-"));
    directories.push(home);
    const cache = join(home, ".gemini", "antigravity-cli", "cache");
    mkdirSync(cache, { recursive: true });
    writeFileSync(join(cache, "onboarding.json"), JSON.stringify({ consumerOnboardingComplete: true }));
    const config = await setup(undefined, { env: { HOME: home } });
    expect(config.availableProviders).toEqual(["agy"]);
    expect(config.defaultProvider).toBe("agy");
  });

  it("boots with a Grok-only login", async () => {
    const home = mkdtempSync(join(tmpdir(), "chatkjb-grok-only-"));
    directories.push(home);
    const grokHome = join(home, ".grok");
    mkdirSync(grokHome, { recursive: true });
    writeFileSync(join(grokHome, "auth.json"), JSON.stringify({ issuer: { key: "token" } }));
    const config = await setup(undefined, { env: { HOME: home } });
    expect(config.availableProviders).toEqual(["grok"]);
    expect(config.defaultProvider).toBe("grok");
  });

  it("collects additional account tokens for failover", async () => {
    const config = await setup("sk-ant-oat01-primary-1", {
      token2: "sk-ant-oat01-secondary-2"
    });
    expect(config.claudeCodeOauthTokens).toEqual([
      "sk-ant-oat01-primary-1",
      "sk-ant-oat01-secondary-2"
    ]);
  });

  it("ignores blank additional tokens and de-duplicates", async () => {
    const config = await setup("sk-ant-oat01-primary-1", {
      token2: "   ",
      token3: "sk-ant-oat01-primary-1"
    });
    expect(config.claudeCodeOauthTokens).toEqual(["sk-ant-oat01-primary-1"]);
  });

  it("rejects malformed additional tokens", async () => {
    await expect(
      setup("sk-ant-oat01-primary-1", { token2: "nope" })
    ).rejects.toThrow();
  });
});

describe("Telegram user authorization configuration", () => {
  it("keeps the existing single allowed user ID behavior", async () => {
    const config = await setup("sk-ant-oat01-test_token-123");
    expect(config.allowedUserId).toBe(1);
    expect(config.allowedUserIds).toEqual([1]);
  });

  it("loads multiple allowed user IDs from CSV", async () => {
    const config = await setup("sk-ant-oat01-test_token-123", {
      telegramAllowedUserIds: "1, 2,3"
    });
    expect(config.allowedUserId).toBe(1);
    expect(config.allowedUserIds).toEqual([1, 2, 3]);
  });

  it("supports plural user IDs without the legacy single setting", async () => {
    const config = await setup("sk-ant-oat01-test_token-123", {
      telegramAllowedUserId: undefined,
      telegramAllowedUserIds: "7,8,7"
    });
    expect(config.allowedUserId).toBe(7);
    expect(config.allowedUserIds).toEqual([7, 8]);
  });

  it("rejects malformed allowed user IDs", async () => {
    await expect(
      setup("sk-ant-oat01-test_token-123", { telegramAllowedUserIds: "1,nope" })
    ).rejects.toThrow("텔레그램 사용자 ID가 정수가 아닙니다");
  });

  it("keeps direct topic deletion sync disabled without MTProto credentials", async () => {
    const config = await setup("sk-ant-oat01-test_token-123");
    expect(config.telegramMtproto).toBeNull();
  });

  it("loads paired MTProto credentials for exact topic deletion sync", async () => {
    const sessionPath = join(tmpdir(), "chatkjb-mtproto-test.session");
    const config = await setup("sk-ant-oat01-test_token-123", {
      env: {
        TELEGRAM_API_ID: "12345678",
        TELEGRAM_API_HASH: "0123456789abcdef0123456789abcdef",
        TELEGRAM_MTPROTO_SESSION_PATH: sessionPath
      }
    });
    expect(config.telegramMtproto).toEqual({
      apiId: 12345678,
      apiHash: "0123456789abcdef0123456789abcdef",
      sessionPath
    });
  });

  it("rejects incomplete or malformed MTProto credentials", async () => {
    await expect(setup("sk-ant-oat01-test_token-123", {
      env: { TELEGRAM_API_ID: "12345678" }
    })).rejects.toThrow("TELEGRAM_API_ID and TELEGRAM_API_HASH must be configured together");
    await expect(setup("sk-ant-oat01-test_token-123", {
      env: {
        TELEGRAM_API_ID: "12345678",
        TELEGRAM_API_HASH: "not-a-hash"
      }
    })).rejects.toThrow("TELEGRAM_API_HASH must be a 32-character hexadecimal string");
  });
});

describe("portable host configuration", () => {
  it("fills missing settings from .env even when a Telegram token is already exported", async () => {
    const directory = mkdtempSync(join(tmpdir(), "chatkjb-partial-env-"));
    directories.push(directory);
    const project = join(directory, "project");
    mkdirSync(project);
    const projectsPath = join(directory, "projects.json");
    writeFileSync(projectsPath, JSON.stringify([
      { name: "test", cwd: project, defaultMode: "auto" }
    ]));
    const envPath = join(directory, ".env");
    writeFileSync(envPath, [
      "TELEGRAM_BOT_TOKEN=1234567890:file-token",
      "TELEGRAM_ALLOWED_USER_ID=42",
      "TELEGRAM_CHAT_ID=-10042",
      "CLAUDE_CODE_OAUTH_TOKEN=sk-ant-oat01-file-token",
      "TZ=Europe/Paris"
    ].join("\n"));
    chmodSync(envPath, 0o600);
    process.env = {
      TELEGRAM_BOT_TOKEN: "1234567890:exported-token",
      CHATKJB_ENV_PATH: envPath,
      PROJECTS_PATH: projectsPath
    };
    const { loadConfig } = await import("../src/config.js");
    const config = await loadConfig();
    expect(config.telegramBotToken).toBe("1234567890:exported-token");
    expect(config.allowedUserIds).toEqual([42]);
    expect(process.env.TZ).toBe("Europe/Paris");
  });

  it("expands home-relative project paths", async () => {
    const directory = mkdtempSync(join(tmpdir(), "chatkjb-project-path-"));
    directories.push(directory);
    const projectsPath = join(directory, "projects.json");
    writeFileSync(projectsPath, JSON.stringify([
      { name: "home-project", cwd: "~/work/example", defaultMode: "auto" }
    ]));
    process.env.CHATKJB_SKIP_PROJECT_DIRECTORY_VALIDATION = "1";
    const { loadProjects } = await import("../src/config.js");
    const projects = await loadProjects(projectsPath);
    expect(projects[0]?.cwd).toBe(join(homedir(), "work", "example"));
  });

  it("uses automatic network selection by default and accepts explicit IP families", async () => {
    const automatic = await setup("sk-ant-oat01-test_token-123");
    expect(automatic.telegramIpFamily).toBe("auto");

    const ipv6 = await setup("sk-ant-oat01-test_token-123", {
      env: { TELEGRAM_IP_FAMILY: "6" }
    });
    expect(ipv6.telegramIpFamily).toBe("6");
  });

  it("rejects an invalid deployment time zone", async () => {
    await expect(setup("sk-ant-oat01-test_token-123", {
      env: { TZ: "not/a-time-zone" }
    })).rejects.toThrow("TZ must be a valid IANA time zone");
  });
});

describe("project configuration", () => {
  it("uses auto when a registered project omits its permission default", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const project = join(directory, "project");
    mkdirSync(project);
    const projectsPath = join(directory, "projects.json");
    writeFileSync(projectsPath, JSON.stringify([{ name: "project", cwd: project }]));
    const { loadProjects } = await import("../src/config.js");

    await expect(loadProjects(projectsPath)).resolves.toMatchObject([
      { name: "project", defaultMode: "auto" }
    ]);
  });

  it("resolves project names and aliases case-insensitively", async () => {
    const { resolveProject } = await import("../src/config.js");
    const projects = [{
      name: "Main Project",
      aliases: ["main", "업무"],
      cwd: "/tmp",
      defaultMode: "default" as const
    }];

    expect(resolveProject(projects, "MAIN")).toBe(projects[0]);
    expect(resolveProject(projects, "업무")).toBe(projects[0]);
  });

  it("rejects aliases that collide with another project name", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const first = join(directory, "first");
    const second = join(directory, "second");
    mkdirSync(first);
    mkdirSync(second);
    const projectsPath = join(directory, "projects.json");
    writeFileSync(projectsPath, JSON.stringify([
      { name: "first", aliases: ["SECOND"], cwd: first, defaultMode: "default" },
      { name: "second", cwd: second, defaultMode: "default" }
    ]));
    const { loadProjects } = await import("../src/config.js");

    await expect(loadProjects(projectsPath)).rejects.toThrow("Duplicate project name or alias");
  });

  it("skips an unreachable project path and keeps the reachable ones", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const good = join(directory, "good");
    mkdirSync(good);
    const projectsPath = join(directory, "projects.json");
    writeFileSync(projectsPath, JSON.stringify([
      { name: "good", cwd: good, defaultMode: "default" },
      { name: "bad", cwd: join(directory, "missing"), defaultMode: "default" }
    ]));
    const warnSpy = vi.spyOn(console, "warn").mockImplementation(() => {});
    const { loadProjects } = await import("../src/config.js");
    const projects = await loadProjects(projectsPath);
    expect(projects).toHaveLength(1);
    expect(projects[0]!.name).toBe("good");
    expect(warnSpy).toHaveBeenCalled();
    warnSpy.mockRestore();
  });

  it("allows no reachable registered projects", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const projectsPath = join(directory, "projects.json");
    writeFileSync(projectsPath, JSON.stringify([
      { name: "first", cwd: join(directory, "missing1"), defaultMode: "default" },
      { name: "second", cwd: join(directory, "missing2"), defaultMode: "default" }
    ]));
    const warnSpy = vi.spyOn(console, "warn").mockImplementation(() => {});
    const { loadProjects } = await import("../src/config.js");
    await expect(loadProjects(projectsPath)).resolves.toEqual([]);
    expect(warnSpy).toHaveBeenCalledTimes(2);
    warnSpy.mockRestore();
  });

  it("allows a missing projects file", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const { loadProjects } = await import("../src/config.js");

    await expect(loadProjects(join(directory, "projects.json"))).resolves.toEqual([]);
  });

  it("still rejects duplicate paths among resolvable projects", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const shared = join(directory, "shared");
    mkdirSync(shared);
    const projectsPath = join(directory, "projects.json");
    writeFileSync(projectsPath, JSON.stringify([
      { name: "first", cwd: shared, defaultMode: "default" },
      { name: "second", cwd: shared, defaultMode: "default" }
    ]));
    const { loadProjects } = await import("../src/config.js");
    await expect(loadProjects(projectsPath)).rejects.toThrow("Duplicate project path");
  });

});

describe("STT configuration", () => {
  it("keeps local STT disabled by default with a configurable large-v3 model path", async () => {
    const config = await setup("sk-ant-oat01-test_token-123");
    expect(config.stt.enabled).toBe(false);
    expect(config.stt.modelPath).toMatch(/ggml-large-v3\.bin$/);
    expect(config.stt.language).toBe("auto");
    expect(config.stt.threads).toBe(8);
    expect(config.stt.timeoutMs).toBe(300_000);
    // 실행기는 절대 경로로 해석되어야 한다(PATH 최소 환경 대비).
    expect(config.stt.whisperCli.length).toBeGreaterThan(0);
    expect(config.stt.ffmpeg.length).toBeGreaterThan(0);
    expect(config.stt.prompt).toMatch(/한국어와 영어/);
  });

  it("uses the custom STT_PROMPT verbatim when provided", async () => {
    const config = await setup("sk-ant-oat01-test_token-123", {
      env: { STT_PROMPT: "commit, push, PR" }
    });
    expect(config.stt.prompt).toBe("commit, push, PR");
  });

  it("treats STT_ENABLED='false' as disabled (not a truthy string)", async () => {
    const config = await setup("sk-ant-oat01-test_token-123", { env: { STT_ENABLED: "false" } });
    expect(config.stt.enabled).toBe(false);
  });

  it("honors STT_ENABLED='0' and 'off' as disabled", async () => {
    expect((await setup("sk-ant-oat01-test_token-123", { env: { STT_ENABLED: "0" } })).stt.enabled).toBe(false);
    vi.resetModules();
    expect((await setup("sk-ant-oat01-test_token-123", { env: { STT_ENABLED: "off" } })).stt.enabled).toBe(false);
  });

  it("honors STT overrides", async () => {
    const config = await setup("sk-ant-oat01-test_token-123", {
      env: { STT_LANGUAGE: "ko", STT_THREADS: "12", STT_TIMEOUT_SECONDS: "120" }
    });
    expect(config.stt.language).toBe("ko");
    expect(config.stt.threads).toBe(12);
    expect(config.stt.timeoutMs).toBe(120_000);
  });
});
