import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";

const originalEnv = { ...process.env };
const directories: string[] = [];

afterEach(() => {
  process.env = { ...originalEnv };
  vi.resetModules();
  for (const directory of directories.splice(0)) {
    rmSync(directory, { recursive: true, force: true });
  }
});

async function setup(token?: string, extra?: {
  token2?: string;
  token3?: string;
  telegramAllowedUserId?: string | undefined;
  telegramAllowedUserIds?: string;
}) {
  const directory = mkdtempSync(join(tmpdir(), "telegram-claude-config-"));
  directories.push(directory);
  const project = join(directory, "project");
  mkdirSync(project);
  const projectsPath = join(directory, "projects.json");
  writeFileSync(projectsPath, JSON.stringify([
    { name: "test", cwd: project, defaultMode: "default" }
  ]));
  process.env = {
    TELEGRAM_BOT_TOKEN: "1234567890:test-token",
    ...(extra && Object.hasOwn(extra, "telegramAllowedUserId")
      ? { TELEGRAM_ALLOWED_USER_ID: extra.telegramAllowedUserId }
      : { TELEGRAM_ALLOWED_USER_ID: "1" }),
    ...(extra?.telegramAllowedUserIds !== undefined
      ? { TELEGRAM_ALLOWED_USER_IDS: extra.telegramAllowedUserIds }
      : {}),
    TELEGRAM_CHAT_ID: "-1001",
    PROJECTS_PATH: projectsPath,
    CLAUDE_CODE_OAUTH_TOKEN: token ?? "",
    GEMINI_API_KEY: "test.gemini-api-key-value-12345678901234567890",
    ...(extra?.token2 !== undefined ? { CLAUDE_CODE_OAUTH_TOKEN_2: extra.token2 } : {}),
    ...(extra?.token3 !== undefined ? { CLAUDE_CODE_OAUTH_TOKEN_3: extra.token3 } : {})
  };
  const { loadConfig } = await import("../src/config.js");
  return loadConfig();
}

describe("OAuth configuration", () => {
  it("requires a setup-token OAuth credential", async () => {
    await expect(setup()).rejects.toThrow();
    await expect(setup("not-an-oauth-token")).rejects.toThrow(
      "CLAUDE_CODE_OAUTH_TOKEN must be generated by `claude setup-token`"
    );
  });

  it("loads a valid setup-token credential", async () => {
    const config = await setup("sk-ant-oat01-test_token-123");
    expect(config.claudeCodeOauthToken).toBe("sk-ant-oat01-test_token-123");
    expect(config.claudeCodeOauthTokens).toEqual(["sk-ant-oat01-test_token-123"]);
    expect(config.claudeMemoryDir).toMatch(/\.claude\/memory$/);
  });

  it("collects additional account tokens for failover", async () => {
    const config = await setup("sk-ant-oat01-primary-1", {
      token2: "sk-ant-oat01-secondary-2"
    });
    expect(config.claudeCodeOauthTokens).toEqual([
      "sk-ant-oat01-primary-1",
      "sk-ant-oat01-secondary-2"
    ]);
  });

  it("ignores blank additional tokens and de-duplicates", async () => {
    const config = await setup("sk-ant-oat01-primary-1", {
      token2: "   ",
      token3: "sk-ant-oat01-primary-1"
    });
    expect(config.claudeCodeOauthTokens).toEqual(["sk-ant-oat01-primary-1"]);
  });

  it("rejects malformed additional tokens", async () => {
    await expect(
      setup("sk-ant-oat01-primary-1", { token2: "nope" })
    ).rejects.toThrow();
  });
});

describe("Telegram user authorization configuration", () => {
  it("keeps the existing single allowed user ID behavior", async () => {
    const config = await setup("sk-ant-oat01-test_token-123");
    expect(config.allowedUserId).toBe(1);
    expect(config.allowedUserIds).toEqual([1]);
  });

  it("loads multiple allowed user IDs from CSV", async () => {
    const config = await setup("sk-ant-oat01-test_token-123", {
      telegramAllowedUserIds: "1, 2,3"
    });
    expect(config.allowedUserId).toBe(1);
    expect(config.allowedUserIds).toEqual([1, 2, 3]);
  });

  it("supports plural user IDs without the legacy single setting", async () => {
    const config = await setup("sk-ant-oat01-test_token-123", {
      telegramAllowedUserId: undefined,
      telegramAllowedUserIds: "7,8,7"
    });
    expect(config.allowedUserId).toBe(7);
    expect(config.allowedUserIds).toEqual([7, 8]);
  });

  it("rejects malformed allowed user IDs", async () => {
    await expect(
      setup("sk-ant-oat01-test_token-123", { telegramAllowedUserIds: "1,nope" })
    ).rejects.toThrow("텔레그램 사용자 ID가 정수가 아닙니다");
  });
});

describe("project configuration", () => {
  it("resolves project names and aliases case-insensitively", async () => {
    const { resolveProject } = await import("../src/config.js");
    const projects = [{
      name: "Main Project",
      aliases: ["main", "업무"],
      cwd: "/tmp",
      defaultMode: "default" as const
    }];

    expect(resolveProject(projects, "MAIN")).toBe(projects[0]);
    expect(resolveProject(projects, "업무")).toBe(projects[0]);
  });

  it("rejects aliases that collide with another project name", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const first = join(directory, "first");
    const second = join(directory, "second");
    mkdirSync(first);
    mkdirSync(second);
    const projectsPath = join(directory, "projects.json");
    writeFileSync(projectsPath, JSON.stringify([
      { name: "first", aliases: ["SECOND"], cwd: first, defaultMode: "default" },
      { name: "second", cwd: second, defaultMode: "default" }
    ]));
    const { loadProjects } = await import("../src/config.js");

    await expect(loadProjects(projectsPath)).rejects.toThrow("Duplicate project name or alias");
  });

  it("skips an unreachable project path and keeps the reachable ones", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const good = join(directory, "good");
    mkdirSync(good);
    const projectsPath = join(directory, "projects.json");
    writeFileSync(projectsPath, JSON.stringify([
      { name: "good", cwd: good, defaultMode: "default" },
      { name: "bad", cwd: join(directory, "missing"), defaultMode: "default" }
    ]));
    const warnSpy = vi.spyOn(console, "warn").mockImplementation(() => {});
    const { loadProjects } = await import("../src/config.js");
    const projects = await loadProjects(projectsPath);
    expect(projects).toHaveLength(1);
    expect(projects[0]!.name).toBe("good");
    expect(warnSpy).toHaveBeenCalled();
    warnSpy.mockRestore();
  });

  it("allows no reachable registered projects", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const projectsPath = join(directory, "projects.json");
    writeFileSync(projectsPath, JSON.stringify([
      { name: "first", cwd: join(directory, "missing1"), defaultMode: "default" },
      { name: "second", cwd: join(directory, "missing2"), defaultMode: "default" }
    ]));
    const warnSpy = vi.spyOn(console, "warn").mockImplementation(() => {});
    const { loadProjects } = await import("../src/config.js");
    await expect(loadProjects(projectsPath)).resolves.toEqual([]);
    expect(warnSpy).toHaveBeenCalledTimes(2);
    warnSpy.mockRestore();
  });

  it("allows a missing projects file", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const { loadProjects } = await import("../src/config.js");

    await expect(loadProjects(join(directory, "projects.json"))).resolves.toEqual([]);
  });

  it("still rejects duplicate paths among resolvable projects", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const shared = join(directory, "shared");
    mkdirSync(shared);
    const projectsPath = join(directory, "projects.json");
    writeFileSync(projectsPath, JSON.stringify([
      { name: "first", cwd: shared, defaultMode: "default" },
      { name: "second", cwd: shared, defaultMode: "default" }
    ]));
    const { loadProjects } = await import("../src/config.js");
    await expect(loadProjects(projectsPath)).rejects.toThrow("Duplicate project path");
  });

  it("adds an absolute directory using its folder name", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const existing = join(directory, "existing");
    const added = join(directory, "Sample Project");
    mkdirSync(existing);
    mkdirSync(added);
    const projectsPath = join(directory, "projects.json");
    const projects = [{ name: "existing", cwd: existing, defaultMode: "default" as const }];
    writeFileSync(projectsPath, JSON.stringify(projects));
    const { addProject } = await import("../src/config.js");

    const project = await addProject(projectsPath, projects, added);

    expect(project).toEqual({
      name: "Sample Project",
      cwd: realpathSync(added),
      defaultMode: "auto"
    });
    expect(JSON.parse(readFileSync(projectsPath, "utf8"))).toHaveLength(2);
  });

  it("repairs a moved project when the old path is missing and the folder name matches", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const oldParent = join(directory, "old");
    const newParent = join(directory, "new");
    const oldPath = join(oldParent, "Application Form");
    const newPath = join(newParent, "Application Form");
    mkdirSync(oldParent);
    mkdirSync(newParent);
    mkdirSync(newPath);
    const projectsPath = join(directory, "projects.json");
    const projects = [{
      name: "Application Form",
      aliases: ["forms"],
      cwd: oldPath,
      defaultMode: "default" as const
    }];
    writeFileSync(projectsPath, JSON.stringify(projects));
    const { addProject } = await import("../src/config.js");

    const project = await addProject(projectsPath, projects, newPath);

    expect(project).toEqual({
      name: "Application Form",
      aliases: ["forms"],
      cwd: realpathSync(newPath),
      defaultMode: "default"
    });
    expect(JSON.parse(readFileSync(projectsPath, "utf8"))).toEqual([project]);
  });

  it("removes a project by name or alias and rewrites projects.json", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const first = join(directory, "first");
    const second = join(directory, "second");
    mkdirSync(first);
    mkdirSync(second);
    const projectsPath = join(directory, "projects.json");
    const projects = [
      { name: "first", aliases: ["uno"], cwd: first, defaultMode: "default" as const },
      { name: "second", cwd: second, defaultMode: "default" as const }
    ];
    writeFileSync(projectsPath, JSON.stringify(projects));
    const { removeProject } = await import("../src/config.js");

    const removed = await removeProject(projectsPath, projects, "UNO");

    expect(removed.name).toBe("first");
    const remaining = JSON.parse(readFileSync(projectsPath, "utf8")) as Array<{ name: string }>;
    expect(remaining).toHaveLength(1);
    expect(remaining[0]!.name).toBe("second");
  });

  it("rejects removing an unknown project", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const only = join(directory, "only");
    mkdirSync(only);
    const projectsPath = join(directory, "projects.json");
    const projects = [{ name: "only", cwd: only, defaultMode: "default" as const }];
    writeFileSync(projectsPath, JSON.stringify(projects));
    const { removeProject } = await import("../src/config.js");

    await expect(removeProject(projectsPath, projects, "missing")).rejects.toThrow(
      "찾을 수 없습니다"
    );
  });

  it("allows removing the last registered project", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const only = join(directory, "only");
    mkdirSync(only);
    const projectsPath = join(directory, "projects.json");
    const projects = [{ name: "only", cwd: only, defaultMode: "default" as const }];
    writeFileSync(projectsPath, JSON.stringify(projects));
    const { removeProject } = await import("../src/config.js");

    const removed = await removeProject(projectsPath, projects, "only");

    expect(removed.name).toBe("only");
    expect(JSON.parse(readFileSync(projectsPath, "utf8"))).toEqual([]);
  });

  it("rejects relative and duplicate project paths", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const projectPath = join(directory, "project");
    mkdirSync(projectPath);
    const projectsPath = join(directory, "projects.json");
    const projects = [{ name: "project", cwd: projectPath, defaultMode: "default" as const }];
    writeFileSync(projectsPath, JSON.stringify(projects));
    const { addProject } = await import("../src/config.js");

    await expect(addProject(projectsPath, projects, "relative/path")).rejects.toThrow(
      "절대경로"
    );
    await expect(addProject(projectsPath, projects, projectPath)).rejects.toThrow(
      "이미 등록된"
    );
  });
});
