import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";

const originalEnv = { ...process.env };
const directories: string[] = [];

afterEach(() => {
  process.env = { ...originalEnv };
  vi.resetModules();
  for (const directory of directories.splice(0)) {
    rmSync(directory, { recursive: true, force: true });
  }
});

async function setup(token?: string) {
  const directory = mkdtempSync(join(tmpdir(), "telegram-claude-config-"));
  directories.push(directory);
  const project = join(directory, "project");
  mkdirSync(project);
  const projectsPath = join(directory, "projects.json");
  writeFileSync(projectsPath, JSON.stringify([
    { name: "test", cwd: project, defaultMode: "default" }
  ]));
  process.env = {
    TELEGRAM_BOT_TOKEN: "1234567890:test-token",
    TELEGRAM_ALLOWED_USER_ID: "1",
    TELEGRAM_CHAT_ID: "-1001",
    PROJECTS_PATH: projectsPath,
    CLAUDE_CODE_OAUTH_TOKEN: token ?? ""
  };
  const { loadConfig } = await import("../src/config.js");
  return loadConfig();
}

describe("OAuth configuration", () => {
  it("requires a setup-token OAuth credential", async () => {
    await expect(setup()).rejects.toThrow();
    await expect(setup("not-an-oauth-token")).rejects.toThrow(
      "CLAUDE_CODE_OAUTH_TOKEN must be generated by `claude setup-token`"
    );
  });

  it("loads a valid setup-token credential", async () => {
    const config = await setup("sk-ant-oat01-test_token-123");
    expect(config.claudeCodeOauthToken).toBe("sk-ant-oat01-test_token-123");
    expect(config.claudeMemoryDir).toMatch(/\.claude\/memory$/);
  });
});

describe("project configuration", () => {
  it("resolves project names and aliases case-insensitively", async () => {
    const { resolveProject } = await import("../src/config.js");
    const projects = [{
      name: "Main Project",
      aliases: ["main", "업무"],
      cwd: "/tmp",
      defaultMode: "default" as const
    }];

    expect(resolveProject(projects, "MAIN")).toBe(projects[0]);
    expect(resolveProject(projects, "업무")).toBe(projects[0]);
  });

  it("rejects aliases that collide with another project name", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const first = join(directory, "first");
    const second = join(directory, "second");
    mkdirSync(first);
    mkdirSync(second);
    const projectsPath = join(directory, "projects.json");
    writeFileSync(projectsPath, JSON.stringify([
      { name: "first", aliases: ["SECOND"], cwd: first, defaultMode: "default" },
      { name: "second", cwd: second, defaultMode: "default" }
    ]));
    const { loadProjects } = await import("../src/config.js");

    await expect(loadProjects(projectsPath)).rejects.toThrow("Duplicate project name or alias");
  });

  it("adds an absolute directory using its folder name", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const existing = join(directory, "existing");
    const added = join(directory, "Sample Project");
    mkdirSync(existing);
    mkdirSync(added);
    const projectsPath = join(directory, "projects.json");
    const projects = [{ name: "existing", cwd: existing, defaultMode: "default" as const }];
    writeFileSync(projectsPath, JSON.stringify(projects));
    const { addProject } = await import("../src/config.js");

    const project = await addProject(projectsPath, projects, added);

    expect(project).toEqual({
      name: "Sample Project",
      cwd: realpathSync(added),
      defaultMode: "default"
    });
    expect(JSON.parse(readFileSync(projectsPath, "utf8"))).toHaveLength(2);
  });

  it("rejects relative and duplicate project paths", async () => {
    const directory = mkdtempSync(join(tmpdir(), "telegram-claude-projects-"));
    directories.push(directory);
    const projectPath = join(directory, "project");
    mkdirSync(projectPath);
    const projectsPath = join(directory, "projects.json");
    const projects = [{ name: "project", cwd: projectPath, defaultMode: "default" as const }];
    writeFileSync(projectsPath, JSON.stringify(projects));
    const { addProject } = await import("../src/config.js");

    await expect(addProject(projectsPath, projects, "relative/path")).rejects.toThrow(
      "절대경로"
    );
    await expect(addProject(projectsPath, projects, projectPath)).rejects.toThrow(
      "이미 등록된"
    );
  });
});
