export const BOT_COMMANDS: ReadonlyArray<{ command: string; description: string; }> = [
  { command: "new", description: "새 작업 시작 (Claude/Codex/Antigravity/Grok)" },
  { command: "catbot", description: "프로젝트 카탈로그 즉시 갱신" },
  { command: "start", description: "도움말과 기본값 패널 표시" },
  { command: "firstp", description: "새 세션 기본 제공자 선택" },
  { command: "reserve", description: "지정 시각에 새 작업 시작" },
  { command: "cancel", description: "대기 중인 예약 작업 선택 취소" },
  { command: "tokenid", description: "새 Codex 세션 시작 전 사용할 계정 번호 지정" },
  { command: "status", description: "오케스트레이터와 현재 작업 상태" },
  { command: "doctor", description: "실행 환경 진단" },
  { command: "sessions", description: "최근 세션 목록" },
  { command: "usage", description: "현재 한도 사용량" },
  { command: "ustoken", description: "전 에이전트 누적 토큰" },
  { command: "steer", description: "실행 중 작업에 즉시 지시" },
  { command: "shotgun", description: "현재 작업 사과·재검토·수정 (모든 제공자)" },
  { command: "next", description: "현재 작업 뒤 후속 작업 예약" },
  { command: "goal", description: "목표 설정 — Claude/Codex 네이티브 goal 우선" },
  { command: "deepinterview", description: "요구사항을 질문·점수화해 spec으로 확정" },
  { command: "ralplan", description: "Planner·Architect·Critic 합의 계획" },
  { command: "ultragoal", description: "영속 목표 장부로 구현·검증 완료" },
  { command: "restop", description: "한도 회복 후 자동 재개 취소" },
  { command: "resume", description: "직전 작업을 기존 문맥에서 재개" },
  { command: "route", description: "작업에 적합한 제공자(Claude/Codex/Antigravity/Grok) 추천" },
  { command: "synth", description: "여러 제공자 답을 비교·심사 후 장점 통합" },
  { command: "query", description: "LLM-Wiki에 질문 (인용 포함 답변)" },
  { command: "compile", description: "LLM-Wiki inbox를 자동 컴파일" },
  { command: "dpbot", description: "완료된 세션 transcript를 LLM-Wiki inbox로 덤프" },
  { command: "stop", description: "현재 토픽 작업 중단" },
  { command: "fork", description: "현재 세션 분기" },
  { command: "compact", description: "현재 세션 컨텍스트 압축" },
  { command: "memory", description: "현재 세션을 전역 메모리에 기록" },
  { command: "mode", description: "권한 모드 확인 또는 변경" },
  { command: "provider", description: "현재 세션 제공자 확인 또는 변경" },
  { command: "model", description: "현재 제공자의 모델 확인 또는 변경" },
  { command: "thinking", description: "Claude 확장적 사고 on/off 확인 또는 변경" },
  { command: "power", description: "현재 AI 작업량/추론 강도 확인 또는 변경" },
  { command: "lean", description: "최소 구현 원칙 확인 또는 변경" },
  { command: "reset", description: "세션 문맥만 초기화" },
  { command: "diff", description: "프로젝트 git diff 요약" },
  { command: "delete", description: "토픽과 로컬 세션 삭제" }
];

export type BotCommandLifecycle =
  | "session-independent"
  | "pending-modifier"
  | "start-capable"
  | "existing-session-required";

/**
 * 새 토픽의 첫 명령 처리 계약을 감사하기 위한 단일 분류표입니다.
 * 공개 메뉴 명령뿐 아니라 의도적으로 숨긴 호환 명령도 모두 포함합니다.
 */
export const BOT_COMMAND_LIFECYCLE = {
  new: "session-independent",
  catbot: "session-independent",
  start: "session-independent",
  firstp: "session-independent",
  reserve: "session-independent",
  cancel: "session-independent",
  tokenid: "pending-modifier",
  status: "session-independent",
  doctor: "session-independent",
  sessions: "session-independent",
  usage: "session-independent",
  ustoken: "session-independent",
  steer: "existing-session-required",
  shotgun: "existing-session-required",
  next: "existing-session-required",
  goal: "start-capable",
  deepinterview: "start-capable",
  ralplan: "start-capable",
  ultragoal: "start-capable",
  restop: "existing-session-required",
  resume: "existing-session-required",
  route: "session-independent",
  synth: "existing-session-required",
  query: "existing-session-required",
  compile: "session-independent",
  dpbot: "session-independent",
  stop: "existing-session-required",
  fork: "existing-session-required",
  compact: "existing-session-required",
  memory: "existing-session-required",
  mode: "existing-session-required",
  provider: "existing-session-required",
  model: "existing-session-required",
  thinking: "existing-session-required",
  power: "existing-session-required",
  effort: "existing-session-required",
  lean: "existing-session-required",
  reset: "existing-session-required",
  diff: "existing-session-required",
  upload: "existing-session-required",
  delete: "existing-session-required"
} as const satisfies Readonly<Record<string, BotCommandLifecycle>>;
