import "dotenv/config";
import {
  accessSync,
  constants,
  existsSync,
  realpathSync,
  statSync
} from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, isAbsolute, join, resolve } from "node:path";
import { z } from "zod";
import { FALLBACK_MODEL_CATALOG } from "./model-catalog.js";
import type { ProjectConfig } from "./types.js";

export const CLAUDE_OAUTH_TOKEN_PATTERN = /^sk-ant-oat01-[A-Za-z0-9_-]+$/;
const projectIdentifierPattern = /^[\p{L}\p{N}][\p{L}\p{N} _.-]*$/u;

// 추가 계정 토큰: 비어 있으면 undefined로 취급해 무시한다.
const optionalOauthToken = z.preprocess(
  (value) => (typeof value === "string" && value.trim() === "" ? undefined : value),
  z.string().regex(
    CLAUDE_OAUTH_TOKEN_PATTERN,
    "추가 OAuth 토큰은 `claude setup-token`으로 생성한 형식이어야 합니다."
  ).optional()
);

const environmentSchema = z.object({
  TELEGRAM_BOT_TOKEN: z.string().min(10),
  TELEGRAM_ALLOWED_USER_ID: z.coerce.number().int(),
  TELEGRAM_CHAT_ID: z.coerce.number().int(),
  CLAUDE_CODE_OAUTH_TOKEN: z.string().regex(
    CLAUDE_OAUTH_TOKEN_PATTERN,
    "CLAUDE_CODE_OAUTH_TOKEN must be generated by `claude setup-token`"
  ),
  // 두 번째/세 번째 계정 토큰(선택). 한도 도달 시 자동 페일오버 대상이 된다.
  CLAUDE_CODE_OAUTH_TOKEN_2: optionalOauthToken,
  CLAUDE_CODE_OAUTH_TOKEN_3: optionalOauthToken,
  DATABASE_PATH: z.string().default("./data/state.sqlite"),
  PROJECTS_PATH: z.string().default("./projects.json"),
  APPROVAL_TIMEOUT_MINUTES: z.coerce.number().positive().default(30),
  STATUS_DEBOUNCE_MS: z.coerce.number().int().min(1000).default(2500),
  MCP_TOOL_TIMEOUT_SECONDS: z.coerce.number().int().min(10).default(60),
  MCP_MAX_ATTEMPTS: z.coerce.number().int().min(1).max(10).default(3),
  CODEX_MCP_TIMEOUT_MINUTES: z.coerce.number().int().min(1).default(30),
  CODEX_MCP_HEARTBEAT_SECONDS: z.coerce.number().int().min(10).default(60),
  LONG_RUNNING_MCP_SERVERS: z.string().default("codex,obsidian"),
  TURN_IDLE_TIMEOUT_MINUTES: z.coerce.number().int().min(1).default(35),
  CLAUDE_MEMORY_DIR: z.string().default("~/.claude/memory"),
  FILE_INBOX_DIR: z.string().default("~/.claude/channels/telegram/inbox"),
  CLAUDE_CODE_EXECUTABLE: z.string().optional(),
  AGY_EXECUTABLE: z.string().optional()
});

const projectSchema = z.object({
  name: z.string().trim().min(1).max(32).regex(
    projectIdentifierPattern,
    "project name may contain letters, numbers, spaces, periods, underscores, and hyphens"
  ),
  aliases: z.array(z.string().trim().min(1).max(32).regex(
    projectIdentifierPattern,
    "project alias may contain letters, numbers, spaces, periods, underscores, and hyphens"
  )).optional(),
  cwd: z.string().min(1),
  defaultMode: z.enum(["default", "acceptEdits", "plan", "dontAsk", "auto"]).default("auto")
});

function normalizeProject(project: z.infer<typeof projectSchema>): ProjectConfig {
  return {
    name: project.name,
    ...(project.aliases ? { aliases: project.aliases } : {}),
    cwd: project.cwd,
    defaultMode: project.defaultMode
  };
}

export type AppConfig = Awaited<ReturnType<typeof loadConfig>>;

function absolutePath(path: string): string {
  const expanded = path.trim().replace(/^~(?=\/|$)/, homedir());
  return isAbsolute(expanded) ? expanded : resolve(process.cwd(), expanded);
}

// agy 바이너리 경로를 정한다. 데몬 PATH에 ~/.local/bin이 없을 수 있어, 명시 env가 없으면
// 표준 설치 경로(~/.local/bin/agy)를 확인하고, 없으면 PATH의 "agy"에 맡긴다.
function resolveAgyExecutable(explicit: string | undefined): string {
  if (explicit && explicit.trim()) return absolutePath(explicit);
  const local = join(homedir(), ".local", "bin", "agy");
  return existsSync(local) ? local : "agy";
}

function validateEnvironmentFile(): void {
  const path = resolve(process.cwd(), ".env");
  if (!existsSync(path)) return;
  const permissions = statSync(path).mode & 0o777;
  if (permissions !== 0o600) {
    throw new Error(`.env permissions must be 0600, received ${permissions.toString(8)}`);
  }
}

function validateProjectDirectory(path: string): string {
  accessSync(path, constants.R_OK | constants.W_OK);
  const canonical = realpathSync(path);
  if (!statSync(canonical).isDirectory()) {
    throw new Error(`Project path is not a directory: ${path}`);
  }
  return canonical;
}

function validateUniqueProjects(projects: ProjectConfig[]): void {
  const identifiers = new Map<string, string>();
  const paths = new Set<string>();
  for (const project of projects) {
    for (const identifier of [project.name, ...(project.aliases ?? [])]) {
      const key = identifier.toLocaleLowerCase("en-US");
      const existing = identifiers.get(key);
      if (existing) {
        throw new Error(`Duplicate project name or alias: ${identifier} (${existing})`);
      }
      identifiers.set(key, project.name);
    }
    const canonical = validateProjectDirectory(project.cwd);
    if (paths.has(canonical)) {
      throw new Error(`Duplicate project path: ${project.cwd}`);
    }
    paths.add(canonical);
  }
}

export function resolveProject(
  projects: ProjectConfig[],
  identifier: string
): ProjectConfig | undefined {
  const key = identifier.trim().toLocaleLowerCase("en-US");
  if (!key) return undefined;
  return projects.find((project) =>
    project.name.toLocaleLowerCase("en-US") === key
    || project.aliases?.some((alias) => alias.toLocaleLowerCase("en-US") === key)
  );
}

function uniqueProjectName(path: string, projects: ProjectConfig[]): string {
  const raw = basename(path)
    .replace(/[^\p{L}\p{N} _.-]/gu, "-")
    .replace(/\s+/g, " ")
    .replace(/^[ ._-]+|[ ._-]+$/g, "")
    .slice(0, 32) || "project";
  const names = new Set(projects.flatMap((project) =>
    [project.name, ...(project.aliases ?? [])].map((name) => name.toLocaleLowerCase("en-US"))
  ));
  if (!names.has(raw.toLocaleLowerCase("en-US"))) return raw;
  for (let index = 2; ; index += 1) {
    const suffix = `-${index}`;
    const candidate = `${raw.slice(0, 32 - suffix.length)}${suffix}`;
    if (!names.has(candidate.toLocaleLowerCase("en-US"))) return candidate;
  }
}

export async function loadProjects(path: string): Promise<ProjectConfig[]> {
  const { readFile } = await import("node:fs/promises");
  const raw = JSON.parse(await readFile(absolutePath(path), "utf8")) as unknown;
  const projects = z.array(projectSchema).min(1).parse(raw).map(normalizeProject);
  validateUniqueProjects(projects);
  return projects;
}

async function persistProjects(
  projectsPath: string,
  projects: ProjectConfig[]
): Promise<void> {
  const { rename, writeFile } = await import("node:fs/promises");
  const target = absolutePath(projectsPath);
  const temporary = join(dirname(target), `.${basename(target)}.${process.pid}.tmp`);
  await writeFile(temporary, `${JSON.stringify(projects, null, 2)}\n`, {
    encoding: "utf8",
    mode: 0o644
  });
  await rename(temporary, target);
}

export async function addProject(
  projectsPath: string,
  projects: ProjectConfig[],
  inputPath: string
): Promise<ProjectConfig> {
  const expanded = inputPath.trim().replace(/^~(?=\/|$)/, process.env.HOME ?? "~");
  if (!isAbsolute(expanded)) {
    throw new Error("프로젝트 경로는 절대경로여야 합니다.");
  }
  const cwd = validateProjectDirectory(expanded);
  if (projects.some((project) => validateProjectDirectory(project.cwd) === cwd)) {
    throw new Error("이미 등록된 프로젝트 경로입니다.");
  }

  const project = normalizeProject(projectSchema.parse({
    name: uniqueProjectName(cwd, projects),
    cwd,
    defaultMode: "auto"
  }));
  const updated = [...projects, project];
  validateUniqueProjects(updated);
  await persistProjects(projectsPath, updated);
  return project;
}

export async function removeProject(
  projectsPath: string,
  projects: ProjectConfig[],
  identifier: string
): Promise<ProjectConfig> {
  const project = resolveProject(projects, identifier);
  if (!project) {
    throw new Error("등록된 프로젝트를 찾을 수 없습니다.");
  }
  if (projects.length <= 1) {
    throw new Error("마지막 프로젝트는 삭제할 수 없습니다. 최소 한 개는 남아 있어야 합니다.");
  }
  const updated = projects.filter((item) => item.name !== project.name);
  await persistProjects(projectsPath, updated);
  return project;
}

export async function loadConfig() {
  validateEnvironmentFile();
  const env = environmentSchema.parse(process.env);
  const projectsPath = absolutePath(env.PROJECTS_PATH);
  const projects = await loadProjects(projectsPath);

  // 기본 토큰 + 선택적 추가 토큰. 중복은 제거하고 등록 순서를 우선순위로 사용한다.
  const claudeCodeOauthTokens = [
    ...new Set(
      [
        env.CLAUDE_CODE_OAUTH_TOKEN,
        env.CLAUDE_CODE_OAUTH_TOKEN_2,
        env.CLAUDE_CODE_OAUTH_TOKEN_3
      ].filter((token): token is string => Boolean(token))
    )
  ];
  // 실제 카탈로그는 시작 시 index.ts가 제공사에서 읽어 config.modelCatalog에 채운다.
  // 여기서는 정적 fallback을 둬, 설정 로드 단계가 외부 프로세스를 띄우지 않게 한다.
  const modelCatalog = FALLBACK_MODEL_CATALOG;

  return {
    telegramBotToken: env.TELEGRAM_BOT_TOKEN,
    allowedUserId: env.TELEGRAM_ALLOWED_USER_ID,
    chatId: env.TELEGRAM_CHAT_ID,
    claudeCodeOauthToken: env.CLAUDE_CODE_OAUTH_TOKEN,
    claudeCodeOauthTokens,
    modelCatalog,
    databasePath: absolutePath(env.DATABASE_PATH),
    projectsPath,
    projects,
    claudeMemoryDir: absolutePath(env.CLAUDE_MEMORY_DIR),
    fileInboxDir: absolutePath(env.FILE_INBOX_DIR),
    approvalTimeoutMs: env.APPROVAL_TIMEOUT_MINUTES * 60_000,
    statusDebounceMs: env.STATUS_DEBOUNCE_MS,
    mcpToolTimeoutMs: env.MCP_TOOL_TIMEOUT_SECONDS * 1000,
    mcpMaxAttempts: env.MCP_MAX_ATTEMPTS,
    codexMcpTimeoutMs: env.CODEX_MCP_TIMEOUT_MINUTES * 60_000,
    codexMcpHeartbeatMs: env.CODEX_MCP_HEARTBEAT_SECONDS * 1000,
    longRunningMcpServers: new Set(
      env.LONG_RUNNING_MCP_SERVERS.split(",")
        .map((name) => name.trim().toLowerCase())
        .filter(Boolean)
    ),
    // 턴 유휴 워치독: 스트림이 이 시간 넘게 완전 침묵하면 먹통으로 보고 abort.
    // 가장 긴 per-server 타임아웃(codex)과 승인 대기 타임아웃을 모두 넘도록 클램프해
    // 정상 장기 작업/승인 대기를 오인 중단하지 않게 한다.
    turnIdleTimeoutMs: Math.max(
      env.TURN_IDLE_TIMEOUT_MINUTES * 60_000,
      env.CODEX_MCP_TIMEOUT_MINUTES * 60_000 + 300_000,
      env.APPROVAL_TIMEOUT_MINUTES * 60_000 + 300_000
    ),
    claudeCodeExecutable: env.CLAUDE_CODE_EXECUTABLE,
    agyExecutable: resolveAgyExecutable(env.AGY_EXECUTABLE)
  };
}
