import { config as loadDotenv } from "dotenv";
import {
  accessSync,
  constants,
  existsSync,
  readFileSync,
  realpathSync,
  statSync
} from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, isAbsolute, join, resolve } from "node:path";
import { z } from "zod";
import { FALLBACK_MODEL_CATALOG } from "./model-catalog.js";
import { filesystemPath } from "./filesystem-path.js";
import { projectSourceDir } from "./runtime-paths.js";
import type { ProjectConfig } from "./types.js";

export const CLAUDE_OAUTH_TOKEN_PATTERN = /^sk-ant-oat01-[A-Za-z0-9_-]+$/;
const projectIdentifierPattern = /^[\p{L}\p{N}][\p{L}\p{N} _.-]*$/u;

// 추가 계정 토큰: 비어 있으면 undefined로 취급해 무시한다.
const optionalOauthToken = z.preprocess(
  (value) => (typeof value === "string" && value.trim() === "" ? undefined : value),
  z.string().regex(
    CLAUDE_OAUTH_TOKEN_PATTERN,
    "추가 OAuth 토큰은 `claude setup-token`으로 생성한 형식이어야 합니다."
  ).optional()
);

const optionalTelegramAllowedUserIds = z.preprocess(
  (value) => (typeof value === "string" && value.trim() === "" ? undefined : value),
  z.string().optional()
);

const optionalGeminiApiKey = z.preprocess(
  (value) => (typeof value === "string" && value.trim() === "" ? undefined : value),
  z.string().trim().min(30).regex(
    /^[A-Za-z0-9._-]+$/,
    "GEMINI_API_KEY contains unsupported characters"
  ).optional()
);

const environmentSchema = z.object({
  TELEGRAM_BOT_TOKEN: z.string().min(10),
  TELEGRAM_ALLOWED_USER_ID: z.coerce.number().int().optional(),
  TELEGRAM_ALLOWED_USER_IDS: optionalTelegramAllowedUserIds,
  TELEGRAM_CHAT_ID: z.coerce.number().int(),
  CLAUDE_CODE_OAUTH_TOKEN: z.string().regex(
    CLAUDE_OAUTH_TOKEN_PATTERN,
    "CLAUDE_CODE_OAUTH_TOKEN must be generated by `claude setup-token`"
  ),
  // 두 번째/세 번째 계정 토큰(선택). 한도 도달 시 자동 페일오버 대상이 된다.
  CLAUDE_CODE_OAUTH_TOKEN_2: optionalOauthToken,
  CLAUDE_CODE_OAUTH_TOKEN_3: optionalOauthToken,
  DATABASE_PATH: z.string().default("./data/state.sqlite"),
  PROJECTS_PATH: z.string().default("./projects.json"),
  APPROVAL_TIMEOUT_MINUTES: z.coerce.number().positive().default(30),
  STATUS_DEBOUNCE_MS: z.coerce.number().int().min(1000).default(2500),
  MCP_TOOL_TIMEOUT_SECONDS: z.coerce.number().int().min(10).default(60),
  MCP_MAX_ATTEMPTS: z.coerce.number().int().min(1).max(10).default(3),
  // 여러 Codex ChatGPT 계정의 CODEX_HOME 디렉터리(CSV, 절대경로). 비어 있으면 단일 계정.
  CODEX_ACCOUNT_HOMES: z.string().optional(),
  CODEX_MCP_TIMEOUT_MINUTES: z.coerce.number().int().min(1).default(30),
  CODEX_MCP_HEARTBEAT_SECONDS: z.coerce.number().int().min(10).default(60),
  LONG_RUNNING_MCP_SERVERS: z.string().default("codex,obsidian"),
  TURN_IDLE_TIMEOUT_MINUTES: z.coerce.number().int().min(1).default(35),
  CLAUDE_MEMORY_DIR: z.string().default("~/.claude/memory"),
  FILE_INBOX_DIR: z.string().default("~/.claude/channels/telegram/inbox"),
  CLAUDE_CODE_EXECUTABLE: z.string().optional(),
  AGY_BACKEND: z.enum(["api", "cli"]).default("api"),
  AGY_EXECUTABLE: z.string().optional(),
  GEMINI_API_KEY: optionalGeminiApiKey,
  AGY_SDK_PYTHON: z.string().optional()
});

const projectSchema = z.object({
  name: z.string().trim().min(1).max(32).regex(
    projectIdentifierPattern,
    "project name may contain letters, numbers, spaces, periods, underscores, and hyphens"
  ),
  aliases: z.array(z.string().trim().min(1).max(32).regex(
    projectIdentifierPattern,
    "project alias may contain letters, numbers, spaces, periods, underscores, and hyphens"
  )).optional(),
  cwd: z.string().min(1),
  defaultMode: z.enum(["default", "acceptEdits", "plan", "dontAsk", "auto"]).default("auto")
});

function skipProjectDirectoryValidation(): boolean {
  return process.env.CHATKJB_SKIP_PROJECT_DIRECTORY_VALIDATION === "1";
}

function normalizeProject(project: z.infer<typeof projectSchema>): ProjectConfig {
  return {
    name: project.name,
    ...(project.aliases ? { aliases: project.aliases } : {}),
    cwd: filesystemPath(project.cwd),
    defaultMode: project.defaultMode
  };
}

export type AppConfig = Awaited<ReturnType<typeof loadConfig>>;

function projectBaseDir(): string {
  const configured = process.env.CHATKJB_CONFIG_BASE_DIR?.trim();
  return configured ? resolve(configured) : projectSourceDir();
}

function absolutePath(path: string): string {
  const expanded = path.trim().replace(/^~(?=\/|$)/, homedir());
  return isAbsolute(expanded) ? expanded : resolve(projectBaseDir(), expanded);
}

export function parseTelegramAllowedUserIds(
  singleUserId: number | undefined,
  rawUserIds: string | undefined
): number[] {
  const ids = [
    singleUserId,
    ...(rawUserIds
      ? rawUserIds.split(",").map((part) => {
          const trimmed = part.trim();
          if (!/^-?\d+$/.test(trimmed)) {
            throw new Error(`텔레그램 사용자 ID가 정수가 아닙니다: ${part}`);
          }
          return Number(trimmed);
        })
      : [])
  ].filter((id): id is number => id !== undefined);
  if (ids.length === 0) {
    throw new Error("TELEGRAM_ALLOWED_USER_ID 또는 TELEGRAM_ALLOWED_USER_IDS가 필요합니다.");
  }
  return [...new Set(ids)];
}

// 여러 Codex 계정의 CODEX_HOME 디렉터리(CSV)를 파싱·검증한다. 각 홈은 디렉터리여야 하고
// 내부에 auth_mode가 "chatgpt"인 auth.json이 있어야 한다(구독 로그인만 허용). 비어 있으면
// 폴백 홈 1개만 반환해 단일 계정 동작과 하위호환을 유지한다.
export function parseCodexAccountHomes(
  raw: string | undefined,
  fallbackHome: string
): string[] {
  if (raw === undefined || raw.trim() === "") {
    return [fallbackHome];
  }
  const entries = raw.split(",").map((part) => part.trim()).filter(Boolean);
  const seen = new Set<string>();
  const result: string[] = [];
  for (const entry of entries) {
    const absPath = absolutePath(entry);
    if (!existsSync(absPath) || !statSync(absPath).isDirectory()) {
      throw new Error(`Codex 계정 홈이 디렉터리가 아닙니다: ${entry}`);
    }
    const authPath = join(absPath, "auth.json");
    if (!existsSync(authPath)) {
      throw new Error(`Codex 계정 홈에 auth.json이 없습니다: ${entry}`);
    }
    let auth: unknown;
    try {
      auth = JSON.parse(readFileSync(authPath, "utf8")) as unknown;
    } catch {
      throw new Error(`Codex auth.json을 읽을 수 없습니다: ${entry}`);
    }
    if (
      typeof auth !== "object"
      || auth === null
      || (auth as Record<string, unknown>)["auth_mode"] !== "chatgpt"
    ) {
      throw new Error(`Codex 계정은 ChatGPT 구독 로그인이어야 합니다(auth_mode!=chatgpt): ${entry}`);
    }
    // 검증을 통과한 뒤에야 canonical 경로로 중복을 제거한다(존재하지 않는 경로에서 realpath가
    // 먼저 던지지 않도록 순서를 지킨다). 등록 순서는 보존한다.
    const canonical = realpathSync(absPath);
    if (seen.has(canonical)) continue;
    seen.add(canonical);
    result.push(absPath);
  }
  return result.length > 0 ? result : [fallbackHome];
}

// agy 바이너리 경로를 정한다. 데몬 PATH에 ~/.local/bin이 없을 수 있어, 명시 env가 없으면
// 표준 설치 경로(~/.local/bin/agy)를 확인하고, 없으면 PATH의 "agy"에 맡긴다.
function resolveAgyExecutable(explicit: string | undefined): string {
  if (explicit && explicit.trim()) return absolutePath(explicit);
  const local = join(homedir(), ".local", "bin", "agy");
  return existsSync(local) ? local : "agy";
}

function validateEnvironmentFile(path = resolve(projectBaseDir(), ".env")): void {
  if (!existsSync(path)) return;
  const permissions = statSync(path).mode & 0o777;
  if (permissions !== 0o600) {
    throw new Error(`.env permissions must be 0600, received ${permissions.toString(8)}`);
  }
}

function validateProjectDirectory(path: string): string {
  const fsPath = filesystemPath(path);
  if (skipProjectDirectoryValidation()) {
    return fsPath;
  }
  accessSync(fsPath, constants.R_OK | constants.W_OK);
  const canonical = realpathSync(fsPath);
  if (!statSync(canonical).isDirectory()) {
    throw new Error(`Project path is not a directory: ${path}`);
  }
  return canonical;
}

// 경로에 접근할 수 없는 프로젝트(예: 이름이 바뀐 NAS 폴더)는 치명적 오류로 처리하지 않고
// 건너뛴다. 단 한 개의 unreachable 경로가 전체 config 로드를 중단시켜 데몬이 KeepAlive로
// 무한 재시작하던 문제(2026-06-28)를 막기 위함이다. 해석에 성공한 프로젝트들에 대해서는
// 기존의 이름/별칭 중복, 경로 중복 검사를 그대로 유지한다. unreachable 항목은
// projects.json에서 삭제하지 않으므로 NAS가 다시 마운트되고 데몬이 재시작되면 자동으로
// 복구된다. 등록 프로젝트를 쓰지 않는 폴더 선택 흐름을 위해 빈 목록도 허용한다.
function validateUniqueProjects(projects: ProjectConfig[]): ProjectConfig[] {
  const identifiers = new Map<string, string>();
  const paths = new Set<string>();
  const reachable: ProjectConfig[] = [];
  for (const project of projects) {
    let canonical: string;
    try {
      canonical = validateProjectDirectory(project.cwd);
    } catch (error) {
      const reason = error instanceof Error ? error.message : String(error);
      console.warn(
        `프로젝트 "${project.name}" 경로에 접근할 수 없어 건너뜁니다: ${project.cwd} (${reason})`
      );
      continue;
    }
    for (const identifier of [project.name, ...(project.aliases ?? [])]) {
      const key = identifier.toLocaleLowerCase("en-US");
      const existing = identifiers.get(key);
      if (existing) {
        throw new Error(`Duplicate project name or alias: ${identifier} (${existing})`);
      }
      identifiers.set(key, project.name);
    }
    if (paths.has(canonical)) {
      throw new Error(`Duplicate project path: ${project.cwd}`);
    }
    paths.add(canonical);
    reachable.push(project);
  }
  return reachable;
}

export function resolveProject(
  projects: ProjectConfig[],
  identifier: string
): ProjectConfig | undefined {
  const key = identifier.trim().toLocaleLowerCase("en-US");
  if (!key) return undefined;
  return projects.find((project) =>
    project.name.toLocaleLowerCase("en-US") === key
    || project.aliases?.some((alias) => alias.toLocaleLowerCase("en-US") === key)
  );
}

function projectNameFromPath(path: string): string {
  return basename(path)
    .replace(/[^\p{L}\p{N} _.-]/gu, "-")
    .replace(/\s+/g, " ")
    .replace(/^[ ._-]+|[ ._-]+$/g, "")
    .slice(0, 32) || "project";
}

function uniqueProjectName(path: string, projects: ProjectConfig[]): string {
  const raw = projectNameFromPath(path);
  const names = new Set(projects.flatMap((project) =>
    [project.name, ...(project.aliases ?? [])].map((name) => name.toLocaleLowerCase("en-US"))
  ));
  if (!names.has(raw.toLocaleLowerCase("en-US"))) return raw;
  for (let index = 2; ; index += 1) {
    const suffix = `-${index}`;
    const candidate = `${raw.slice(0, 32 - suffix.length)}${suffix}`;
    if (!names.has(candidate.toLocaleLowerCase("en-US"))) return candidate;
  }
}

export async function loadProjects(path: string): Promise<ProjectConfig[]> {
  const { readFile } = await import("node:fs/promises");
  let contents: string;
  try {
    contents = await readFile(absolutePath(path), "utf8");
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      return [];
    }
    throw error;
  }
  const raw = JSON.parse(contents) as unknown;
  const projects = z.array(projectSchema).parse(raw).map(normalizeProject);
  // unreachable 경로는 건너뛰고 해석에 성공한 프로젝트만 런타임에 사용한다.
  return validateUniqueProjects(projects);
}

async function persistProjects(
  projectsPath: string,
  projects: ProjectConfig[]
): Promise<void> {
  const { rename, writeFile } = await import("node:fs/promises");
  const target = absolutePath(projectsPath);
  const temporary = join(dirname(target), `.${basename(target)}.${process.pid}.tmp`);
  await writeFile(temporary, `${JSON.stringify(projects, null, 2)}\n`, {
    encoding: "utf8",
    mode: 0o644
  });
  await rename(temporary, target);
}

export async function addProject(
  projectsPath: string,
  projects: ProjectConfig[],
  inputPath: string
): Promise<ProjectConfig> {
  const expanded = inputPath.trim().replace(/^~(?=\/|$)/, process.env.HOME ?? "~");
  if (!isAbsolute(expanded)) {
    throw new Error("프로젝트 경로는 절대경로여야 합니다.");
  }
  const cwd = validateProjectDirectory(expanded);
  for (const project of projects) {
    try {
      if (validateProjectDirectory(project.cwd) === cwd) {
        throw new Error("이미 등록된 프로젝트 경로입니다.");
      }
    } catch (error) {
      if (error instanceof Error && error.message === "이미 등록된 프로젝트 경로입니다.") {
        throw error;
      }
      // 이동되거나 삭제된 기존 프로젝트는 아래의 이름 기반 복구 대상이 될 수 있다.
    }
  }

  const inferredName = projectNameFromPath(cwd);
  const staleMatch = projects.find((project) => {
    if (project.name.toLocaleLowerCase("en-US") !== inferredName.toLocaleLowerCase("en-US")) {
      return false;
    }
    try {
      validateProjectDirectory(project.cwd);
      return false;
    } catch {
      return true;
    }
  });
  if (staleMatch) {
    const repaired = normalizeProject(projectSchema.parse({
      ...staleMatch,
      cwd
    }));
    const updated = projects.map((project) =>
      project === staleMatch ? repaired : project
    );
    validateUniqueProjects(updated);
    await persistProjects(projectsPath, updated);
    return repaired;
  }

  const project = normalizeProject(projectSchema.parse({
    name: uniqueProjectName(cwd, projects),
    cwd,
    defaultMode: "auto"
  }));
  const updated = [...projects, project];
  validateUniqueProjects(updated);
  await persistProjects(projectsPath, updated);
  return project;
}

export async function removeProject(
  projectsPath: string,
  projects: ProjectConfig[],
  identifier: string
): Promise<ProjectConfig> {
  const project = resolveProject(projects, identifier);
  if (!project) {
    throw new Error("등록된 프로젝트를 찾을 수 없습니다.");
  }
  const updated = projects.filter((item) => item.name !== project.name);
  await persistProjects(projectsPath, updated);
  return project;
}

export async function loadConfig() {
  const envPath = process.env.CHATKJB_ENV_PATH?.trim()
    ? resolve(process.env.CHATKJB_ENV_PATH)
    : resolve(projectBaseDir(), ".env");
  validateEnvironmentFile(envPath);
  if (!process.env.TELEGRAM_BOT_TOKEN) {
    loadDotenv({ path: envPath, quiet: true });
  }
  const env = environmentSchema.parse(process.env);
  if (env.AGY_BACKEND === "api" && !env.GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY가 필요합니다. Antigravity 구독 CLI 모드는 AGY_BACKEND=cli로 설정하십시오.");
  }
  const allowedUserIds = parseTelegramAllowedUserIds(
    env.TELEGRAM_ALLOWED_USER_ID,
    env.TELEGRAM_ALLOWED_USER_IDS
  );
  const projectsPath = absolutePath(env.PROJECTS_PATH);
  const projects = await loadProjects(projectsPath);

  // 기본 토큰 + 선택적 추가 토큰. 중복은 제거하고 등록 순서를 우선순위로 사용한다.
  const claudeCodeOauthTokens = [
    ...new Set(
      [
        env.CLAUDE_CODE_OAUTH_TOKEN,
        env.CLAUDE_CODE_OAUTH_TOKEN_2,
        env.CLAUDE_CODE_OAUTH_TOKEN_3
      ].filter((token): token is string => Boolean(token))
    )
  ];
  // Codex 계정 홈 목록. 기본 홈은 CODEX_HOME(있으면) 또는 ~/.codex로, session-manager의
  // 해석과 일치시킨다. 미설정이면 이 단일 홈만 담겨 기존 단일 계정 동작과 동일하다.
  const codexFallbackHome = process.env.CODEX_HOME?.trim()
    ? absolutePath(process.env.CODEX_HOME)
    : join(homedir(), ".codex");
  const codexAccountHomes = parseCodexAccountHomes(env.CODEX_ACCOUNT_HOMES, codexFallbackHome);
  // 실제 카탈로그는 시작 시 index.ts가 제공사에서 읽어 config.modelCatalog에 채운다.
  // 여기서는 정적 fallback을 둬, 설정 로드 단계가 외부 프로세스를 띄우지 않게 한다.
  const modelCatalog = FALLBACK_MODEL_CATALOG;

  return {
    telegramBotToken: env.TELEGRAM_BOT_TOKEN,
    allowedUserId: allowedUserIds[0]!,
    allowedUserIds,
    chatId: env.TELEGRAM_CHAT_ID,
    claudeCodeOauthToken: env.CLAUDE_CODE_OAUTH_TOKEN,
    claudeCodeOauthTokens,
    codexAccountHomes,
    modelCatalog,
    databasePath: absolutePath(env.DATABASE_PATH),
    projectsPath,
    projects,
    claudeMemoryDir: absolutePath(env.CLAUDE_MEMORY_DIR),
    fileInboxDir: absolutePath(env.FILE_INBOX_DIR),
    approvalTimeoutMs: env.APPROVAL_TIMEOUT_MINUTES * 60_000,
    statusDebounceMs: env.STATUS_DEBOUNCE_MS,
    mcpToolTimeoutMs: env.MCP_TOOL_TIMEOUT_SECONDS * 1000,
    mcpMaxAttempts: env.MCP_MAX_ATTEMPTS,
    codexMcpTimeoutMs: env.CODEX_MCP_TIMEOUT_MINUTES * 60_000,
    codexMcpHeartbeatMs: env.CODEX_MCP_HEARTBEAT_SECONDS * 1000,
    longRunningMcpServers: new Set(
      env.LONG_RUNNING_MCP_SERVERS.split(",")
        .map((name) => name.trim().toLowerCase())
        .filter(Boolean)
    ),
    // 턴 유휴 워치독: 스트림이 이 시간 넘게 완전 침묵하면 먹통으로 보고 abort.
    // 가장 긴 per-server 타임아웃(codex)과 승인 대기 타임아웃을 모두 넘도록 클램프해
    // 정상 장기 작업/승인 대기를 오인 중단하지 않게 한다.
    turnIdleTimeoutMs: Math.max(
      env.TURN_IDLE_TIMEOUT_MINUTES * 60_000,
      env.CODEX_MCP_TIMEOUT_MINUTES * 60_000 + 300_000,
      env.APPROVAL_TIMEOUT_MINUTES * 60_000 + 300_000
    ),
    claudeCodeExecutable: env.CLAUDE_CODE_EXECUTABLE,
    agyBackend: env.AGY_BACKEND,
    agyExecutable: resolveAgyExecutable(env.AGY_EXECUTABLE),
    geminiApiKey: env.GEMINI_API_KEY,
    agySdkPython: env.AGY_SDK_PYTHON
      ? absolutePath(env.AGY_SDK_PYTHON)
      : join(
        homedir(),
        ".local",
        "share",
        "telegram-claude-orchestrator",
        "agy-sdk",
        "bin",
        "python"
      )
  };
}
