import { config as loadDotenv } from "dotenv";
import {
  accessSync,
  constants,
  existsSync,
  readFileSync,
  realpathSync,
  statSync
} from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, isAbsolute, join, resolve } from "node:path";
import { z } from "zod";
import {
  expandHome,
  resolveAgyExecutable,
  resolveClaudeCodeExecutable,
  resolveCodexExecutable,
  resolveFfmpegExecutable,
  resolveGrokExecutable,
  resolveWhisperCliExecutable
} from "./cli-resolver.js";
import { filesystemPath } from "./filesystem-path.js";
import { isValidTimeZone } from "./localization.js";
import { FALLBACK_MODEL_CATALOG } from "./model-catalog.js";
import { hasReadyClineProvider } from "./cline-sdk.js";
import { projectSourceDir } from "./runtime-paths.js";
import type { ProjectConfig, ProviderKind } from "./types.js";
import { discoverUsageCachePaths, discoverUsageCacheUrls } from "./usage-cache.js";

export const CLAUDE_OAUTH_TOKEN_PATTERN = /^sk-ant-oat01-[A-Za-z0-9_-]+$/;
const projectIdentifierPattern = /^[\p{L}\p{N}][\p{L}\p{N} _.-]*$/u;

// 추가 계정 토큰: 비어 있으면 undefined로 취급해 무시한다.
const optionalOauthToken = z.preprocess(
  (value) => (typeof value === "string" && value.trim() === "" ? undefined : value),
  z.string().regex(
    CLAUDE_OAUTH_TOKEN_PATTERN,
    "추가 OAuth 토큰은 `claude setup-token`으로 생성한 형식이어야 합니다."
  ).optional()
);

const optionalPrimaryOauthToken = z.preprocess(
  (value) => (typeof value === "string" && value.trim() === "" ? undefined : value),
  z.string().regex(
    CLAUDE_OAUTH_TOKEN_PATTERN,
    "CLAUDE_CODE_OAUTH_TOKEN must be generated by `claude setup-token`"
  ).optional()
);

const optionalTelegramAllowedUserIds = z.preprocess(
  (value) => (typeof value === "string" && value.trim() === "" ? undefined : value),
  z.string().optional()
);

const optionalTelegramApiId = z.preprocess(
  (value) => (typeof value === "string" && value.trim() === "" ? undefined : value),
  z.coerce.number().int().positive().optional()
);

const optionalTelegramApiHash = z.preprocess(
  (value) => (typeof value === "string" && value.trim() === "" ? undefined : value),
  z.string().trim().regex(/^[a-f0-9]{32}$/i, "TELEGRAM_API_HASH must be a 32-character hexadecimal string").optional()
);

// 기본 프롬프트는 범용적인 한·영 혼용 안내만 둔다. 전문 용어 사전은 STT_PROMPT로 각자 설정한다.
export const DEFAULT_STT_PROMPT = "다음은 한국어와 영어 전문 용어가 섞인 대화입니다. 영어 고유명사와 기술 용어는 가능한 한 원문 표기로 적으십시오.";

// "false"/"0"/"no"/"off"/"" → false, 그 외 truthy 문자열 → true.
// z.coerce.boolean()은 "false" 문자열조차 true로 만들어 못 쓴다.
const booleanFlag = (defaultValue: boolean) =>
  z.preprocess((value) => {
    if (typeof value !== "string") return value ?? defaultValue;
    const normalized = value.trim().toLowerCase();
    if (normalized === "") return defaultValue;
    return !["false", "0", "no", "off"].includes(normalized);
  }, z.boolean());


const environmentSchema = z.object({
  TELEGRAM_BOT_TOKEN: z.string().min(10),
  TELEGRAM_ALLOWED_USER_ID: z.coerce.number().int().optional(),
  TELEGRAM_ALLOWED_USER_IDS: optionalTelegramAllowedUserIds,
  TELEGRAM_CHAT_ID: z.coerce.number().int(),
  TELEGRAM_IP_FAMILY: z.enum(["auto", "4", "6"]).default("auto"),
  TELEGRAM_API_ID: optionalTelegramApiId,
  TELEGRAM_API_HASH: optionalTelegramApiHash,
  TELEGRAM_MTPROTO_SESSION_PATH: z.string().default("./data/telegram-mtproto.session"),
  TZ: z.string().trim().min(1).refine(isValidTimeZone, "TZ must be a valid IANA time zone").optional(),
  CHATKJB_LOCALE: z.string().trim().min(1).optional(),
  CLAUDE_CODE_OAUTH_TOKEN: optionalPrimaryOauthToken,
  // 두 번째/세 번째 계정 토큰(선택). 한도 도달 시 자동 페일오버 대상이 된다.
  CLAUDE_CODE_OAUTH_TOKEN_2: optionalOauthToken,
  CLAUDE_CODE_OAUTH_TOKEN_3: optionalOauthToken,
  DATABASE_PATH: z.string().default("./data/state.sqlite"),
  PROJECTS_PATH: z.string().default("./projects.json"),
  APPROVAL_TIMEOUT_MINUTES: z.coerce.number().positive().default(30),
  STATUS_DEBOUNCE_MS: z.coerce.number().int().min(1000).default(2500),
  MCP_TOOL_TIMEOUT_SECONDS: z.coerce.number().int().min(10).default(60),
  MCP_MAX_ATTEMPTS: z.coerce.number().int().min(1).max(10).default(3),
  // 여러 Codex ChatGPT 계정의 CODEX_HOME 디렉터리(CSV, 절대경로). 비어 있으면 단일 계정.
  CODEX_ACCOUNT_HOMES: z.string().optional(),
  // Alibaba Cloud Model Studio Token Plan (OpenAI-compatible Codex custom provider).
  DASHSCOPE_API_KEY: z.string().trim().min(1).optional(),
  DASHSCOPE_BASE_URL: z.string().url().default(
    "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1"
  ),
  DASHSCOPE_MODEL: z.string().trim().min(1).default("qwen3.8-max"),
  CODEX_MCP_TIMEOUT_MINUTES: z.coerce.number().int().min(1).default(30),
  // 0이면 provider 턴의 절대 시간 제한을 두지 않는다.
  PROVIDER_TURN_TIMEOUT_MINUTES: z.coerce.number().int().min(0).default(0),
  // 서버발 웹소켓 조기 종료 등 일시적 Codex 스트림 오류에 대해 같은 스레드로 재시도할 최대 횟수.
  // SDK 자체 재연결이 소진된 뒤에도 앱 레벨에서 이 횟수만큼 더 이어붙여 시도한다. 0이면 비활성.
  CODEX_TRANSIENT_STREAM_RETRIES: z.coerce.number().int().min(0).max(10).default(3),
  CODEX_MCP_HEARTBEAT_SECONDS: z.coerce.number().int().min(10).default(60),
  LONG_RUNNING_MCP_SERVERS: z.string().default("codex,obsidian"),
  TURN_IDLE_TIMEOUT_MINUTES: z.coerce.number().int().min(1).default(35),
  CLAUDE_MEMORY_DIR: z.string().default("~/.claude/memory"),
  FILE_INBOX_DIR: z.string().default("~/.claude/channels/telegram/inbox"),
  CLAUDE_CODE_EXECUTABLE: z.string().optional(),
  CODEX_EXECUTABLE: z.string().optional(),
  AGY_EXECUTABLE: z.string().optional(),
  GROK_EXECUTABLE: z.string().optional(),
  GROK_MODEL: z.string().optional(),
  AGY_MCP_SERVERS: z.string().default(
    "llm-wiki,obsidian,outlook,peekaboo,playwright,price-feed,literature-evidence,scihub"
  ),
  // 로컬 음성 받아쓰기(STT). whisper.cpp + ffmpeg, 외부 API/한도 소모 없음.
  STT_ENABLED: booleanFlag(false),
  STT_WHISPER_CLI: z.string().optional(),
  STT_FFMPEG: z.string().optional(),
  STT_MODEL_PATH: z.string().default("~/.local/share/whisper-models/ggml-large-v3.bin"),
  STT_LANGUAGE: z.string().default("auto"),
  // 초기 프롬프트(용어 사전). 한∙영 혼용 시 영어 전문 용어 표기를 바로잡는다.
  // 미설정 시 아래 DEFAULT_STT_PROMPT(사용자 상용 용어)를 쓴다. 빈 문자열로 끄려면 STT_PROMPT=" ".
  STT_PROMPT: z.string().optional(),
  STT_THREADS: z.coerce.number().int().min(1).max(64).default(8),
  STT_TIMEOUT_SECONDS: z.coerce.number().int().min(10).default(300)
}).superRefine((env, ctx) => {
  if ((env.TELEGRAM_API_ID === undefined) === (env.TELEGRAM_API_HASH === undefined)) return;
  ctx.addIssue({
    code: "custom",
    path: env.TELEGRAM_API_ID === undefined ? ["TELEGRAM_API_ID"] : ["TELEGRAM_API_HASH"],
    message: "TELEGRAM_API_ID and TELEGRAM_API_HASH must be configured together"
  });
});

const telegramGuiEnvironmentSchema = z.object({
  TELEGRAM_ALLOWED_USER_ID: z.coerce.number().int().optional(),
  TELEGRAM_ALLOWED_USER_IDS: optionalTelegramAllowedUserIds,
  TELEGRAM_CHAT_ID: z.coerce.number().int().negative(),
  TELEGRAM_API_ID: z.coerce.number().int().positive(),
  TELEGRAM_API_HASH: z.string().trim().regex(
    /^[a-f0-9]{32}$/i,
    "TELEGRAM_API_HASH must be a 32-character hexadecimal string"
  ),
  TELEGRAM_GUI_SESSION_PATH: z.string().trim().min(1).default("./data/telegram-gui.session"),
  TELEGRAM_MTPROTO_SESSION_PATH: z.string().trim().min(1).default("./data/telegram-mtproto.session"),
  DATABASE_PATH: z.preprocess(
    (value) => typeof value === "string" && value.trim() === "" ? undefined : value,
    z.string().trim().min(1).default("./data/state.sqlite")
  ),
  // 작성창 사용량 스트립의 Codex/Grok 라이브 조회용 실행 파일(선택, 없으면 기본 해석).
  CODEX_EXECUTABLE: z.string().optional(),
  GROK_EXECUTABLE: z.string().optional(),
  // 사용량 스트립의 Codex 다계정 조회용 홈 목록(CSV). 미설정이면 CODEX_HOME/~.codex 단일 계정.
  CODEX_ACCOUNT_HOMES: z.string().optional()
});

const projectSchema = z.object({
  name: z.string().trim().min(1).max(32).regex(
    projectIdentifierPattern,
    "project name may contain letters, numbers, spaces, periods, underscores, and hyphens"
  ),
  aliases: z.array(z.string().trim().min(1).max(32).regex(
    projectIdentifierPattern,
    "project alias may contain letters, numbers, spaces, periods, underscores, and hyphens"
  )).optional(),
  cwd: z.string().min(1),
  defaultMode: z.enum(["default", "acceptEdits", "plan", "dontAsk", "auto"]).default("auto")
});

function skipProjectDirectoryValidation(): boolean {
  return process.env.CHATKJB_SKIP_PROJECT_DIRECTORY_VALIDATION === "1";
}

function normalizeProject(project: z.infer<typeof projectSchema>): ProjectConfig {
  return {
    name: project.name,
    ...(project.aliases ? { aliases: project.aliases } : {}),
    cwd: absolutePath(filesystemPath(project.cwd)),
    defaultMode: project.defaultMode
  };
}

export type AppConfig = Awaited<ReturnType<typeof loadConfig>>;
export type TelegramGuiConfig = Awaited<ReturnType<typeof loadTelegramGuiConfig>>;

function projectBaseDir(): string {
  const configured = process.env.CHATKJB_CONFIG_BASE_DIR?.trim();
  return configured ? resolve(expandHome(configured)) : projectSourceDir();
}

function absolutePath(path: string): string {
  const expanded = path.trim().replace(/^~(?=\/|$)/, homedir());
  return isAbsolute(expanded) ? expanded : resolve(projectBaseDir(), expanded);
}

export function parseTelegramAllowedUserIds(
  singleUserId: number | undefined,
  rawUserIds: string | undefined
): number[] {
  const ids = [
    singleUserId,
    ...(rawUserIds
      ? rawUserIds.split(",").map((part) => {
        const trimmed = part.trim();
        if (!/^-?\d+$/.test(trimmed)) {
          throw new Error(`텔레그램 사용자 ID가 정수가 아닙니다: ${part}`);
        }
        return Number(trimmed);
      })
      : [])
  ].filter((id): id is number => id !== undefined);
  if (ids.length === 0) {
    throw new Error("TELEGRAM_ALLOWED_USER_ID 또는 TELEGRAM_ALLOWED_USER_IDS가 필요합니다.");
  }
  return [...new Set(ids)];
}

// 여러 Codex 계정의 CODEX_HOME 디렉터리(CSV)를 파싱·검증한다. 각 홈은 디렉터리여야 하고
// 내부에 auth_mode가 "chatgpt"인 auth.json이 있어야 한다(구독 로그인만 허용). 비어 있으면
// 폴백 홈 1개만 반환해 단일 계정 동작과 하위호환을 유지한다.
export function parseCodexAccountHomes(
  raw: string | undefined,
  fallbackHome: string
): string[] {
  if (raw === undefined || raw.trim() === "") {
    return hasCodexSubscriptionAuth(fallbackHome) ? [fallbackHome] : [];
  }
  const entries = raw.split(",").map((part) => part.trim()).filter(Boolean);
  const seen = new Set<string>();
  const result: string[] = [];
  for (const entry of entries) {
    const absPath = absolutePath(entry);
    if (!existsSync(absPath) || !statSync(absPath).isDirectory()) {
      throw new Error(`Codex 계정 홈이 디렉터리가 아닙니다: ${entry}`);
    }
    const authPath = join(absPath, "auth.json");
    if (!existsSync(authPath)) {
      throw new Error(`Codex 계정 홈에 auth.json이 없습니다: ${entry}`);
    }
    let auth: unknown;
    try {
      auth = JSON.parse(readFileSync(authPath, "utf8")) as unknown;
    } catch {
      throw new Error(`Codex auth.json을 읽을 수 없습니다: ${entry}`);
    }
    if (
      typeof auth !== "object"
      || auth === null
      || (auth as Record<string, unknown>)["auth_mode"] !== "chatgpt"
    ) {
      throw new Error(`Codex 계정은 ChatGPT 구독 로그인이어야 합니다(auth_mode!=chatgpt): ${entry}`);
    }
    // 검증을 통과한 뒤에야 canonical 경로로 중복을 제거한다(존재하지 않는 경로에서 realpath가
    // 먼저 던지지 않도록 순서를 지킨다). 등록 순서는 보존한다.
    const canonical = realpathSync(absPath);
    if (seen.has(canonical)) continue;
    seen.add(canonical);
    result.push(absPath);
  }
  return result.length > 0 ? result : [fallbackHome];
}

function hasCodexSubscriptionAuth(home: string): boolean {
  const authPath = join(home, "auth.json");
  try {
    if (!existsSync(home) || !statSync(home).isDirectory() || !existsSync(authPath)) return false;
    const auth = JSON.parse(readFileSync(authPath, "utf8")) as Record<string, unknown>;
    return auth["auth_mode"] === "chatgpt";
  } catch {
    return false;
  }
}

function hasAgySubscriptionAuth(home: string): boolean {
  const onboardingPath = join(home, ".gemini", "antigravity-cli", "cache", "onboarding.json");
  if (!existsSync(onboardingPath)) return false;
  try {
    const onboarding = JSON.parse(readFileSync(onboardingPath, "utf8")) as Record<string, unknown>;
    return onboarding["onboardingComplete"] === true
      || onboarding["consumerOnboardingComplete"] === true;
  } catch {
    return false;
  }
}

function hasGrokSubscriptionAuth(home: string): boolean {
  const authPath = join(home, ".grok", "auth.json");
  if (!existsSync(authPath)) return false;
  try {
    const auth = JSON.parse(readFileSync(authPath, "utf8")) as Record<string, unknown>;
    return Object.values(auth).some((entry) =>
      !!entry
      && typeof entry === "object"
      && typeof (entry as Record<string, unknown>)["key"] === "string"
      && ((entry as Record<string, unknown>)["key"] as string).trim().length > 0
    );
  } catch {
    return false;
  }
}

export function detectAuthenticatedProviders(options: {
  claudeOauthTokens: readonly string[];
  codexAccountHomes: readonly string[];
  home?: string;
}): ProviderKind[] {
  const home = options.home ?? homedir();
  const providers: ProviderKind[] = [];
  if (options.claudeOauthTokens.length > 0) providers.push("claude");
  if (options.codexAccountHomes.some(hasCodexSubscriptionAuth)) providers.push("codex");
  if (hasAgySubscriptionAuth(home)) providers.push("agy");
  if (hasGrokSubscriptionAuth(home)) providers.push("grok");
  return providers;
}

export function parseMcpServerNames(raw: string | undefined): string[] {
  if (raw === undefined) return [];
  return [...new Set(
    raw.split(",")
      .map((part) => part.trim())
      .filter(Boolean)
  )];
}

function validateEnvironmentFile(path = resolve(projectBaseDir(), ".env")): void {
  if (!existsSync(path)) return;
  const permissions = statSync(path).mode & 0o777;
  if (permissions !== 0o600) {
    throw new Error(`.env permissions must be 0600, received ${permissions.toString(8)}`);
  }
}

function loadEnvironmentFromDotenv(): void {
  const envPath = process.env.CHATKJB_ENV_PATH?.trim()
    ? absolutePath(process.env.CHATKJB_ENV_PATH)
    : resolve(projectBaseDir(), ".env");
  validateEnvironmentFile(envPath);
  // 셸/launchd 환경변수가 우선하고, 빠진 값만 .env에서 채운다.
  loadDotenv({ path: envPath, quiet: true, override: false });
}

function assertDistinctGuiSessionPath(guiPath: string, protectedPath: string, label: string): void {
  const collisionMessage = `TELEGRAM_GUI_SESSION_PATH must be distinct from ${label}`;
  if (canonicalProspectivePath(guiPath) === canonicalProspectivePath(protectedPath)) {
    throw new Error(collisionMessage);
  }
  if (
    existsSync(guiPath)
    && existsSync(protectedPath)
  ) {
    const guiFile = statSync(guiPath);
    const protectedFile = statSync(protectedPath);
    if (
      realpathSync(guiPath) === realpathSync(protectedPath)
      || (guiFile.dev === protectedFile.dev && guiFile.ino === protectedFile.ino)
    ) throw new Error(collisionMessage);
  }
}

function canonicalProspectivePath(path: string): string {
  let existing = path;
  const suffix: string[] = [];
  while (!existsSync(existing)) {
    const parent = dirname(existing);
    if (parent === existing) throw new Error(`Cannot resolve path boundary: ${path}`);
    suffix.unshift(basename(existing));
    existing = parent;
  }
  return resolve(realpathSync(existing), ...suffix);
}

function validateProjectDirectory(path: string): string {
  const fsPath = filesystemPath(path);
  if (skipProjectDirectoryValidation()) {
    return fsPath;
  }
  accessSync(fsPath, constants.R_OK | constants.W_OK);
  const canonical = realpathSync(fsPath);
  if (!statSync(canonical).isDirectory()) {
    throw new Error(`Project path is not a directory: ${path}`);
  }
  return canonical;
}

// 경로에 접근할 수 없는 프로젝트(예: 이름이 바뀐 NAS 폴더)는 치명적 오류로 처리하지 않고
// 건너뛴다. 단 한 개의 unreachable 경로가 전체 config 로드를 중단시켜 데몬이 KeepAlive로
// 무한 재시작하던 문제(2026-06-28)를 막기 위함이다. 해석에 성공한 프로젝트들에 대해서는
// 기존의 이름/별칭 중복, 경로 중복 검사를 그대로 유지한다. unreachable 항목은
// projects.json에서 삭제하지 않으므로 NAS가 다시 마운트되고 데몬이 재시작되면 자동으로
// 복구된다. 등록 프로젝트를 쓰지 않는 폴더 선택 흐름을 위해 빈 목록도 허용한다.
function validateUniqueProjects(projects: ProjectConfig[]): ProjectConfig[] {
  const identifiers = new Map<string, string>();
  const paths = new Set<string>();
  const reachable: ProjectConfig[] = [];
  for (const project of projects) {
    let canonical: string;
    try {
      canonical = validateProjectDirectory(project.cwd);
    } catch (error) {
      const reason = error instanceof Error ? error.message : String(error);
      console.warn(
        `프로젝트 "${project.name}" 경로에 접근할 수 없어 건너뜁니다: ${project.cwd} (${reason})`
      );
      continue;
    }
    for (const identifier of [project.name, ...(project.aliases ?? [])]) {
      const key = identifier.toLocaleLowerCase("en-US");
      const existing = identifiers.get(key);
      if (existing) {
        throw new Error(`Duplicate project name or alias: ${identifier} (${existing})`);
      }
      identifiers.set(key, project.name);
    }
    if (paths.has(canonical)) {
      throw new Error(`Duplicate project path: ${project.cwd}`);
    }
    paths.add(canonical);
    reachable.push(project);
  }
  return reachable;
}

export function resolveProject(
  projects: ProjectConfig[],
  identifier: string
): ProjectConfig | undefined {
  const key = identifier.trim().toLocaleLowerCase("en-US");
  if (!key) return undefined;
  return projects.find((project) =>
    project.name.toLocaleLowerCase("en-US") === key
    || project.aliases?.some((alias) => alias.toLocaleLowerCase("en-US") === key)
  );
}

export async function loadProjects(path: string): Promise<ProjectConfig[]> {
  const { readFile } = await import("node:fs/promises");
  let contents: string;
  try {
    contents = await readFile(absolutePath(path), "utf8");
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      return [];
    }
    throw error;
  }
  const raw = JSON.parse(contents) as unknown;
  const projects = z.array(projectSchema).parse(raw).map(normalizeProject);
  // unreachable 경로는 건너뛰고 해석에 성공한 프로젝트만 런타임에 사용한다.
  return validateUniqueProjects(projects);
}

/**
 * 메인 봇 프로젝트 루트를 찾는다. Terminal GUI는 Application Support 아래에 격리된
 * 설정만 갖고 DATABASE_PATH/CODEX_ACCOUNT_HOMES가 비는 경우가 많아, 사용량 스트립이
 * 봇과 같은 SQLite·Codex 계정을 보려면 이 경로가 필요하다.
 *
 * 우선순위: CHATKJB_PROJECT_DIR → LaunchAgent com.chatkjb.bot → 소스 트리 추정.
 */
export function discoverBotProjectDir(env: NodeJS.ProcessEnv = process.env): string | null {
  const fromEnv = env.CHATKJB_PROJECT_DIR?.trim();
  if (fromEnv) {
    const resolved = resolve(expandHome(fromEnv));
    if (existsSync(resolved) && statSync(resolved).isDirectory()) return resolved;
  }

  const plistPath = join(homedir(), "Library/LaunchAgents/com.chatkjb.bot.plist");
  if (existsSync(plistPath)) {
    try {
      const text = readFileSync(plistPath, "utf8");
      const projectMatch = text.match(/CHATKJB_PROJECT_DIR<\/key>\s*<string>([^<]+)<\/string>/i);
      const project = projectMatch?.[1]?.trim();
      if (project) {
        const resolved = resolve(expandHome(project));
        if (existsSync(resolved) && statSync(resolved).isDirectory()) return resolved;
      }
      const wdMatch = text.match(/<key>\s*WorkingDirectory\s*<\/key>\s*<string>([^<]+)<\/string>/i);
      const workingDirectory = wdMatch?.[1]?.trim();
      if (workingDirectory) {
        const resolved = resolve(expandHome(workingDirectory));
        if (existsSync(resolved) && statSync(resolved).isDirectory()) return resolved;
      }
    } catch {
      // plist 읽기 실패는 다음 후보로 넘어간다.
    }
  }

  const source = projectSourceDir();
  if (
    existsSync(join(source, "data", "state.sqlite"))
    || existsSync(join(source, "projects.json"))
  ) {
    return source;
  }
  return null;
}

/**
 * Terminal GUI .env 에 빠진 사용량 관련 키를 봇 프로젝트 .env 로 채운다.
 * Telegram 인증 키는 이미 로드된 값을 덮어쓰지 않는다(override: false).
 */
function loadBotUsageEnvironment(): void {
  const projectDir = discoverBotProjectDir();
  if (!projectDir) return;
  if (!process.env.CHATKJB_PROJECT_DIR?.trim()) {
    process.env.CHATKJB_PROJECT_DIR = projectDir;
  }
  const botEnvPath = join(projectDir, ".env");
  if (!existsSync(botEnvPath)) return;
  loadDotenv({ path: botEnvPath, quiet: true, override: false });
}

/**
 * 사용량 스트립용 공유 DB 경로를 고른다.
 * Terminal Application Support 기본값(./data/state.sqlite)은 세션 테이블이 비어 있거나
 * 파일이 없을 수 있으므로, 그때는 봇 프로젝트 data/state.sqlite 로 폴백한다.
 */
export function resolveUsageDatabasePath(
  configuredPath: string,
  env: NodeJS.ProcessEnv = process.env
): string {
  const expanded = configuredPath.trim().replace(/^~(?=\/|$)/, homedir());
  const againstConfigBase = isAbsolute(expanded)
    ? expanded
    : resolve(projectBaseDir(), expanded);
  if (existsSync(againstConfigBase)) return againstConfigBase;

  const botProject = discoverBotProjectDir(env);
  if (!botProject) return againstConfigBase;

  if (!isAbsolute(expanded)) {
    const againstBot = resolve(botProject, expanded);
    if (existsSync(againstBot)) return againstBot;
  }
  const defaultBotDb = join(botProject, "data", "state.sqlite");
  if (existsSync(defaultBotDb)) return defaultBotDb;
  return againstConfigBase;
}

export async function loadTelegramGuiConfig() {
  // 1) Terminal/격리 설정의 .env (Telegram 인증 키)
  loadEnvironmentFromDotenv();
  // 2) 봇 프로젝트 .env 로 사용량 관련 누락 키 보충 (DATABASE_PATH, CODEX_ACCOUNT_HOMES 등)
  loadBotUsageEnvironment();
  const env = telegramGuiEnvironmentSchema.parse(process.env);
  const allowedUserIds = parseTelegramAllowedUserIds(
    env.TELEGRAM_ALLOWED_USER_ID,
    env.TELEGRAM_ALLOWED_USER_IDS
  );
  if (allowedUserIds.some((id) => !Number.isSafeInteger(id) || id <= 0)) {
    throw new Error("Telegram GUI allowed user IDs must be positive safe integers");
  }
  const sessionPath = absolutePath(env.TELEGRAM_GUI_SESSION_PATH);
  const botSessionPath = absolutePath(env.TELEGRAM_MTPROTO_SESSION_PATH);
  // 사용량 스트립은 봇 세션 DB를 읽어야 하므로, 격리 설정 기본 경로가 비어 있으면 봇 DB로 폴백.
  const databasePath = resolveUsageDatabasePath(env.DATABASE_PATH);
  assertDistinctGuiSessionPath(sessionPath, botSessionPath, "TELEGRAM_MTPROTO_SESSION_PATH");
  assertDistinctGuiSessionPath(sessionPath, databasePath, "DATABASE_PATH");
  for (const suffix of ["-wal", "-shm", "-journal"] as const) {
    assertDistinctGuiSessionPath(sessionPath, `${databasePath}${suffix}`, "DATABASE_PATH");
  }

  // Codex 계정 홈 폴백 기준. 봇 프로젝트에서 CODEX_HOME이 오면 그쪽을, 없으면 ~/.codex.
  const codexFallbackHome = process.env.CODEX_HOME?.trim()
    ? absolutePath(process.env.CODEX_HOME)
    : join(homedir(), ".codex");

  // Terminal은 위치와 무관하게 데몬이 게시한 공유 캐시만 읽는다. 같은 Mac에서 local
  // 모드를 쓰면 사용량 폴칭마다 Codex 계정별 app-server를 다시 띄워 UI와 시스템을
  // 주기적으로 버벅이게 한다. 실제 provider 조회는 daemon-usage-publisher 한 곳만 맡는다.
  const botProjectDir = discoverBotProjectDir();
  const usageSourceMode = "daemon-cache" as const;
  const usageCachePaths = discoverUsageCachePaths({ projectDir: botProjectDir });
  // 맥북처럼 NAS 미마운트 환경: Tailscale MagicDNS(neam-macmini 등) HTTP 후보.
  const usageCacheUrls = discoverUsageCacheUrls();
  const usageHttpToken = process.env.CHATKJB_USAGE_HTTP_TOKEN?.trim() || undefined;

  return {
    apiId: env.TELEGRAM_API_ID,
    apiHash: env.TELEGRAM_API_HASH,
    chatId: env.TELEGRAM_CHAT_ID,
    allowedUserIds,
    sessionPath,
    // 작성창 사용량 스트립 소스. DB는 읽기 전용으로만 열고, 실행 파일은 메인 봇과 같은
    // 해석 규칙을 쓴다.
    databasePath,
    codexExecutable: resolveCodexExecutable(env.CODEX_EXECUTABLE),
    grokExecutable: resolveGrokExecutable(env.GROK_EXECUTABLE),
    // 사용량 스트립 Codex 다계정 조회 대상. 메인 봇과 동일한 파싱/폴백 규칙을 쓴다.
    codexAccountHomes: parseCodexAccountHomes(
      env.CODEX_ACCOUNT_HOMES,
      codexFallbackHome
    ),
    usageSourceMode,
    // daemon-cache 모드에서는 세 provider 모두 이미 데몬 값을 사용한다.
    preferDaemonClaudeCache: false,
    usageCachePaths,
    usageCacheUrls,
    ...(usageHttpToken ? { usageHttpToken } : {})
  };
}

export async function loadConfig() {
  // 셸/launchd 환경변수가 우선하고, 빠진 값만 .env에서 채운다. 토큰 하나가 이미 export되어
  // 있다는 이유로 TZ·경로 등 나머지 로컬 설정 전체를 건너뛰지 않게 한다.
  loadEnvironmentFromDotenv();
  const env = environmentSchema.parse(process.env);
  const allowedUserIds = parseTelegramAllowedUserIds(
    env.TELEGRAM_ALLOWED_USER_ID,
    env.TELEGRAM_ALLOWED_USER_IDS
  );
  const projectsPath = absolutePath(env.PROJECTS_PATH);
  const projects = await loadProjects(projectsPath);

  // 기본 토큰 + 선택적 추가 토큰. 중복은 제거하고 등록 순서를 우선순위로 사용한다.
  const claudeCodeOauthTokens = [
    ...new Set(
      [
        env.CLAUDE_CODE_OAUTH_TOKEN,
        env.CLAUDE_CODE_OAUTH_TOKEN_2,
        env.CLAUDE_CODE_OAUTH_TOKEN_3
      ].filter((token): token is string => Boolean(token))
    )
  ];
  // Codex 계정 홈 목록. 기본 홈은 CODEX_HOME(있으면) 또는 ~/.codex로, session-manager의
  // 해석과 일치시킨다. 미설정이면 이 단일 홈만 담겨 기존 단일 계정 동작과 동일하다.
  const codexFallbackHome = process.env.CODEX_HOME?.trim()
    ? absolutePath(process.env.CODEX_HOME)
    : join(homedir(), ".codex");
  const codexAccountHomes = parseCodexAccountHomes(env.CODEX_ACCOUNT_HOMES, codexFallbackHome);
  const availableProviders = detectAuthenticatedProviders({
    claudeOauthTokens: claudeCodeOauthTokens,
    codexAccountHomes,
    home: process.env.HOME?.trim() || homedir()
  });
  if (await hasReadyClineProvider().catch(() => false)) availableProviders.push("cline");
  if (availableProviders.length === 0) {
    throw new Error(
      "사용 가능한 AI 제공자 인증이 없습니다. Claude OAuth, Codex ChatGPT 로그인, "
      + "Antigravity OAuth, Grok 로그인 또는 실행 가능한 Cline provider 중 하나 이상이 필요합니다."
    );
  }
  // 실제 카탈로그는 시작 시 index.ts가 제공사에서 읽어 config.modelCatalog에 채운다.
  // 여기서는 정적 fallback을 둬, 설정 로드 단계가 외부 프로세스를 띄우지 않게 한다.
  const modelCatalog = FALLBACK_MODEL_CATALOG;

  return {
    telegramBotToken: env.TELEGRAM_BOT_TOKEN,
    allowedUserId: allowedUserIds[0]!,
    allowedUserIds,
    chatId: env.TELEGRAM_CHAT_ID,
    telegramIpFamily: env.TELEGRAM_IP_FAMILY,
    telegramMtproto: env.TELEGRAM_API_ID !== undefined && env.TELEGRAM_API_HASH !== undefined
      ? {
          apiId: env.TELEGRAM_API_ID,
          apiHash: env.TELEGRAM_API_HASH,
          sessionPath: absolutePath(env.TELEGRAM_MTPROTO_SESSION_PATH)
        }
      : null,
    claudeCodeOauthToken: claudeCodeOauthTokens[0],
    claudeCodeOauthTokens,
    codexAccountHomes,
    ...(env.DASHSCOPE_API_KEY
      ? { alibabaTokenPlan: {
        apiKey: env.DASHSCOPE_API_KEY,
        baseUrl: env.DASHSCOPE_BASE_URL.replace(/\/$/, ""),
        defaultModel: env.DASHSCOPE_MODEL
      } }
      : {}),
    availableProviders,
    defaultProvider: availableProviders[0]!,
    modelCatalog,
    databasePath: absolutePath(env.DATABASE_PATH),
    projectsPath,
    projects,
    claudeMemoryDir: absolutePath(env.CLAUDE_MEMORY_DIR),
    fileInboxDir: absolutePath(env.FILE_INBOX_DIR),
    approvalTimeoutMs: env.APPROVAL_TIMEOUT_MINUTES * 60_000,
    statusDebounceMs: env.STATUS_DEBOUNCE_MS,
    mcpToolTimeoutMs: env.MCP_TOOL_TIMEOUT_SECONDS * 1000,
    mcpMaxAttempts: env.MCP_MAX_ATTEMPTS,
    codexMcpTimeoutMs: env.CODEX_MCP_TIMEOUT_MINUTES * 60_000,
    providerTurnTimeoutMs: env.PROVIDER_TURN_TIMEOUT_MINUTES === 0
      ? undefined
      : env.PROVIDER_TURN_TIMEOUT_MINUTES * 60_000,
    codexTransientStreamRetries: env.CODEX_TRANSIENT_STREAM_RETRIES,
    codexMcpHeartbeatMs: env.CODEX_MCP_HEARTBEAT_SECONDS * 1000,
    longRunningMcpServers: new Set(
      env.LONG_RUNNING_MCP_SERVERS.split(",")
        .map((name) => name.trim().toLowerCase())
        .filter(Boolean)
    ),
    // 턴 유휴 워치독: 스트림이 이 시간 넘게 완전 침묵하면 먹통으로 보고 abort.
    // 가장 긴 per-server 타임아웃(codex)과 승인 대기 타임아웃을 모두 넘도록 클램프해
    // 정상 장기 작업/승인 대기를 오인 중단하지 않게 한다.
    turnIdleTimeoutMs: Math.max(
      env.TURN_IDLE_TIMEOUT_MINUTES * 60_000,
      env.CODEX_MCP_TIMEOUT_MINUTES * 60_000 + 300_000,
      env.APPROVAL_TIMEOUT_MINUTES * 60_000 + 300_000
    ),
    claudeCodeExecutable: resolveClaudeCodeExecutable(env.CLAUDE_CODE_EXECUTABLE),
    codexExecutable: resolveCodexExecutable(env.CODEX_EXECUTABLE),
    agyExecutable: resolveAgyExecutable(env.AGY_EXECUTABLE),
    grokExecutable: resolveGrokExecutable(env.GROK_EXECUTABLE),
    grokModel: env.GROK_MODEL?.trim() || undefined,
    agyMcpServers: parseMcpServerNames(env.AGY_MCP_SERVERS),
    stt: {
      enabled: env.STT_ENABLED,
      whisperCli: resolveWhisperCliExecutable(env.STT_WHISPER_CLI),
      ffmpeg: resolveFfmpegExecutable(env.STT_FFMPEG),
      modelPath: absolutePath(env.STT_MODEL_PATH),
      language: env.STT_LANGUAGE.trim() || "auto",
      prompt: env.STT_PROMPT ?? DEFAULT_STT_PROMPT,
      threads: env.STT_THREADS,
      timeoutMs: env.STT_TIMEOUT_SECONDS * 1000
    }
  };
}
